-- Migration 024: Update activity badge image URLs (cropped from reference)

UPDATE public.badges SET image_url = '/badges/activity/act_001.png' WHERE name = '동네 산책러' AND type = 'activity';
UPDATE public.badges SET image_url = '/badges/activity/act_002.png' WHERE name = '골목길 탐험가' AND type = 'activity';
UPDATE public.badges SET image_url = '/badges/activity/act_003.png' WHERE name = '콘크리트 유랑자' AND type = 'activity';
UPDATE public.badges SET image_url = '/badges/activity/act_004.png' WHERE name = '횡단보도의 지배자' AND type = 'activity';
UPDATE public.badges SET image_url = '/badges/activity/act_005.png' WHERE name = '도심의 순례자' AND type = 'activity';
UPDATE public.badges SET image_url = '/badges/activity/act_006.png' WHERE name = '무념무상의 걸음' AND type = 'activity';
UPDATE public.badges SET image_url = '/badges/activity/act_007.png' WHERE name = '공원의 파수꾼' AND type = 'activity';
UPDATE public.badges SET image_url = '/badges/activity/act_008.png' WHERE name = '발끝의 리듬' AND type = 'activity';
UPDATE public.badges SET image_url = '/badges/activity/act_009.png' WHERE name = '그림자 추적자' AND type = 'activity';
UPDATE public.badges SET image_url = '/badges/activity/act_010.png' WHERE name = '대지의 호흡' AND type = 'activity';
UPDATE public.badges SET image_url = '/badges/activity/act_011.png' WHERE name = '첫 숨결' AND type = 'activity';
UPDATE public.badges SET image_url = '/badges/activity/act_012.png' WHERE name = '심장의 박동' AND type = 'activity';
UPDATE public.badges SET image_url = '/badges/activity/act_013.png' WHERE name = '아스팔트 러너' AND type = 'activity';
UPDATE public.badges SET image_url = '/badges/activity/act_014.png' WHERE name = '바람의 꼬리' AND type = 'activity';
UPDATE public.badges SET image_url = '/badges/activity/act_015.png' WHERE name = '페이스 메이커' AND type = 'activity';
UPDATE public.badges SET image_url = '/badges/activity/act_016.png' WHERE name = '땀방울의 무게' AND type = 'activity';
UPDATE public.badges SET image_url = '/badges/activity/act_017.png' WHERE name = '숨가쁜 환희' AND type = 'activity';
UPDATE public.badges SET image_url = '/badges/activity/act_018.png' WHERE name = '한계의 목격자' AND type = 'activity';
UPDATE public.badges SET image_url = '/badges/activity/act_019.png' WHERE name = '중력을 거스르는 자' AND type = 'activity';
UPDATE public.badges SET image_url = '/badges/activity/act_020.png' WHERE name = '질주의 카타르시스' AND type = 'activity';
UPDATE public.badges SET image_url = '/badges/activity/act_021.png' WHERE name = '멈추지 않는 심장' AND type = 'activity';
UPDATE public.badges SET image_url = '/badges/activity/act_022.png' WHERE name = '고독한 스프린터' AND type = 'activity';
UPDATE public.badges SET image_url = '/badges/activity/act_023.png' WHERE name = '폭풍의 눈' AND type = 'activity';
UPDATE public.badges SET image_url = '/badges/activity/act_024.png' WHERE name = '러너스 하이' AND type = 'activity';
UPDATE public.badges SET image_url = '/badges/activity/act_025.png' WHERE name = '무호흡의 질주' AND type = 'activity';
UPDATE public.badges SET image_url = '/badges/activity/act_026.png' WHERE name = '두 바퀴의 시작' AND type = 'activity';
UPDATE public.badges SET image_url = '/badges/activity/act_027.png' WHERE name = '페달의 노래' AND type = 'activity';
UPDATE public.badges SET image_url = '/badges/activity/act_028.png' WHERE name = '안장 위의 방랑자' AND type = 'activity';
UPDATE public.badges SET image_url = '/badges/activity/act_029.png' WHERE name = '바람을 가르는 자' AND type = 'activity';
UPDATE public.badges SET image_url = '/badges/activity/act_030.png' WHERE name = '기어의 변주곡' AND type = 'activity';
UPDATE public.badges SET image_url = '/badges/activity/act_031.png' WHERE name = '아스팔트 서퍼' AND type = 'activity';
UPDATE public.badges SET image_url = '/badges/activity/act_032.png' WHERE name = '체인의 비명' AND type = 'activity';
UPDATE public.badges SET image_url = '/badges/activity/act_033.png' WHERE name = '허벅지의 반란' AND type = 'activity';
UPDATE public.badges SET image_url = '/badges/activity/act_034.png' WHERE name = '자전거 도로의 유령' AND type = 'activity';
UPDATE public.badges SET image_url = '/badges/activity/act_035.png' WHERE name = '다운힐의 쾌감' AND type = 'activity';
UPDATE public.badges SET image_url = '/badges/activity/act_036.png' WHERE name = '업힐의 지배자' AND type = 'activity';
UPDATE public.badges SET image_url = '/badges/activity/act_037.png' WHERE name = '무한의 기어' AND type = 'activity';
UPDATE public.badges SET image_url = '/badges/activity/act_038.png' WHERE name = '폭주하는 엔진' AND type = 'activity';
UPDATE public.badges SET image_url = '/badges/activity/act_039.png' WHERE name = '광속의 라이더' AND type = 'activity';
UPDATE public.badges SET image_url = '/badges/activity/act_040.png' WHERE name = '두 바퀴의 전설' AND type = 'activity';
UPDATE public.badges SET image_url = '/badges/activity/act_041.png' WHERE name = '언덕의 도전자' AND type = 'activity';
UPDATE public.badges SET image_url = '/badges/activity/act_042.png' WHERE name = '비탈길의 투사' AND type = 'activity';
UPDATE public.badges SET image_url = '/badges/activity/act_043.png' WHERE name = '구름을 향한 발걸음' AND type = 'activity';
UPDATE public.badges SET image_url = '/badges/activity/act_044.png' WHERE name = '하늘과 닿은 자' AND type = 'activity';
UPDATE public.badges SET image_url = '/badges/activity/act_045.png' WHERE name = '고도의 정복자' AND type = 'activity';
UPDATE public.badges SET image_url = '/badges/activity/act_046.png' WHERE name = '산맥의 그림자' AND type = 'activity';
UPDATE public.badges SET image_url = '/badges/activity/act_047.png' WHERE name = '대기의 경계선' AND type = 'activity';
UPDATE public.badges SET image_url = '/badges/activity/act_048.png' WHERE name = '중력의 저항군' AND type = 'activity';
UPDATE public.badges SET image_url = '/badges/activity/act_049.png' WHERE name = '태양과 가장 가까운 곳' AND type = 'activity';
UPDATE public.badges SET image_url = '/badges/activity/act_050.png' WHERE name = '대지의 기둥' AND type = 'activity';
UPDATE public.badges SET image_url = '/badges/activity/act_051.png' WHERE name = '시간의 마술사' AND type = 'activity';
UPDATE public.badges SET image_url = '/badges/activity/act_052.png' WHERE name = '찰나의 몰입' AND type = 'activity';
UPDATE public.badges SET image_url = '/badges/activity/act_053.png' WHERE name = '멈추지 않는 시계' AND type = 'activity';
UPDATE public.badges SET image_url = '/badges/activity/act_054.png' WHERE name = '고요한 지속' AND type = 'activity';
UPDATE public.badges SET image_url = '/badges/activity/act_055.png' WHERE name = '영원의 궤도' AND type = 'activity';
UPDATE public.badges SET image_url = '/badges/activity/act_056.png' WHERE name = '시간의 축적' AND type = 'activity';
UPDATE public.badges SET image_url = '/badges/activity/act_057.png' WHERE name = '끈기의 미학' AND type = 'activity';
UPDATE public.badges SET image_url = '/badges/activity/act_058.png' WHERE name = '멈춤 없는 모래시계' AND type = 'activity';
UPDATE public.badges SET image_url = '/badges/activity/act_059.png' WHERE name = '시간의 지배자' AND type = 'activity';
UPDATE public.badges SET image_url = '/badges/activity/act_060.png' WHERE name = '영원을 걷는 자' AND type = 'activity';
UPDATE public.badges SET image_url = '/badges/activity/act_061.png' WHERE name = '리듬의 발견' AND type = 'activity';
UPDATE public.badges SET image_url = '/badges/activity/act_062.png' WHERE name = '바람의 파편' AND type = 'activity';
UPDATE public.badges SET image_url = '/badges/activity/act_063.png' WHERE name = '가속의 쾌감' AND type = 'activity';
UPDATE public.badges SET image_url = '/badges/activity/act_064.png' WHERE name = '허물어지는 풍경' AND type = 'activity';
UPDATE public.badges SET image_url = '/badges/activity/act_065.png' WHERE name = '쏜살같은 궤적' AND type = 'activity';
UPDATE public.badges SET image_url = '/badges/activity/act_066.png' WHERE name = '질주의 미학' AND type = 'activity';
UPDATE public.badges SET image_url = '/badges/activity/act_067.png' WHERE name = '한계 속도 돌파' AND type = 'activity';
UPDATE public.badges SET image_url = '/badges/activity/act_068.png' WHERE name = '음속의 파편' AND type = 'activity';
UPDATE public.badges SET image_url = '/badges/activity/act_069.png' WHERE name = '빛의 잔상' AND type = 'activity';
UPDATE public.badges SET image_url = '/badges/activity/act_070.png' WHERE name = '차원을 넘은 속도' AND type = 'activity';
UPDATE public.badges SET image_url = '/badges/activity/act_071.png' WHERE name = '작심삼일의 파괴자' AND type = 'activity';
UPDATE public.badges SET image_url = '/badges/activity/act_072.png' WHERE name = '습관의 조각가' AND type = 'activity';
UPDATE public.badges SET image_url = '/badges/activity/act_073.png' WHERE name = '멈추지 않는 톱니바퀴' AND type = 'activity';
UPDATE public.badges SET image_url = '/badges/activity/act_074.png' WHERE name = '매일의 증명' AND type = 'activity';
UPDATE public.badges SET image_url = '/badges/activity/act_075.png' WHERE name = '일상의 기적' AND type = 'activity';
UPDATE public.badges SET image_url = '/badges/activity/act_076.png' WHERE name = '시간의 성벽' AND type = 'activity';
UPDATE public.badges SET image_url = '/badges/activity/act_077.png' WHERE name = '철의 의지' AND type = 'activity';
UPDATE public.badges SET image_url = '/badges/activity/act_078.png' WHERE name = '꺾이지 않는 투지' AND type = 'activity';
UPDATE public.badges SET image_url = '/badges/activity/act_079.png' WHERE name = '영원의 루프' AND type = 'activity';
UPDATE public.badges SET image_url = '/badges/activity/act_080.png' WHERE name = '살아있는 전설' AND type = 'activity';
UPDATE public.badges SET image_url = '/badges/activity/act_081.png' WHERE name = '새벽의 파수꾼' AND type = 'activity';
UPDATE public.badges SET image_url = '/badges/activity/act_082.png' WHERE name = '달빛 산책자' AND type = 'activity';
UPDATE public.badges SET image_url = '/badges/activity/act_083.png' WHERE name = '고요한 밤의 손님' AND type = 'activity';
UPDATE public.badges SET image_url = '/badges/activity/act_084.png' WHERE name = '여명의 추적자' AND type = 'activity';
UPDATE public.badges SET image_url = '/badges/activity/act_085.png' WHERE name = '별빛의 인도자' AND type = 'activity';
UPDATE public.badges SET image_url = '/badges/activity/act_086.png' WHERE name = '어둠을 가르는 자' AND type = 'activity';
UPDATE public.badges SET image_url = '/badges/activity/act_087.png' WHERE name = '새벽의 독주' AND type = 'activity';
UPDATE public.badges SET image_url = '/badges/activity/act_088.png' WHERE name = '첫 햇살의 환영' AND type = 'activity';
UPDATE public.badges SET image_url = '/badges/activity/act_089.png' WHERE name = '그림자 사냥꾼' AND type = 'activity';
UPDATE public.badges SET image_url = '/badges/activity/act_090.png' WHERE name = '밤의 군주' AND type = 'activity';
UPDATE public.badges SET image_url = '/badges/activity/act_091.png' WHERE name = '첫눈의 발자국' AND type = 'activity';
UPDATE public.badges SET image_url = '/badges/activity/act_092.png' WHERE name = '서리 낀 숨결' AND type = 'activity';
UPDATE public.badges SET image_url = '/badges/activity/act_093.png' WHERE name = '얼어붙은 땀방울' AND type = 'activity';
UPDATE public.badges SET image_url = '/badges/activity/act_094.png' WHERE name = '동장군의 친구' AND type = 'activity';
UPDATE public.badges SET image_url = '/badges/activity/act_095.png' WHERE name = '혹한의 심장' AND type = 'activity';
UPDATE public.badges SET image_url = '/badges/activity/act_096.png' WHERE name = '얼음꽃의 주인' AND type = 'activity';
UPDATE public.badges SET image_url = '/badges/activity/act_097.png' WHERE name = '눈보라의 지배자' AND type = 'activity';
UPDATE public.badges SET image_url = '/badges/activity/act_098.png' WHERE name = '태양의 입맞춤' AND type = 'activity';
UPDATE public.badges SET image_url = '/badges/activity/act_099.png' WHERE name = '아지랑이 헌터' AND type = 'activity';
UPDATE public.badges SET image_url = '/badges/activity/act_100.png' WHERE name = '타오르는 투지' AND type = 'activity';
UPDATE public.badges SET image_url = '/badges/activity/act_101.png' WHERE name = '폭염의 정복자' AND type = 'activity';
UPDATE public.badges SET image_url = '/badges/activity/act_102.png' WHERE name = '주간의 땀방울' AND type = 'activity';
UPDATE public.badges SET image_url = '/badges/activity/act_103.png' WHERE name = '일곱 번의 해돋이' AND type = 'activity';
UPDATE public.badges SET image_url = '/badges/activity/act_104.png' WHERE name = '루틴의 마술사' AND type = 'activity';
UPDATE public.badges SET image_url = '/badges/activity/act_105.png' WHERE name = '위클리 챌린저' AND type = 'activity';
UPDATE public.badges SET image_url = '/badges/activity/act_106.png' WHERE name = '7일의 기적' AND type = 'activity';
UPDATE public.badges SET image_url = '/badges/activity/act_107.png' WHERE name = '주간의 정복자' AND type = 'activity';
UPDATE public.badges SET image_url = '/badges/activity/act_108.png' WHERE name = '월화수목금토일' AND type = 'activity';
UPDATE public.badges SET image_url = '/badges/activity/act_109.png' WHERE name = '성실함의 증명' AND type = 'activity';
UPDATE public.badges SET image_url = '/badges/activity/act_110.png' WHERE name = '주간 마일리지' AND type = 'activity';
UPDATE public.badges SET image_url = '/badges/activity/act_111.png' WHERE name = '쉼 없는 일주일' AND type = 'activity';
UPDATE public.badges SET image_url = '/badges/activity/act_112.png' WHERE name = '금주의 MVP' AND type = 'activity';
UPDATE public.badges SET image_url = '/badges/activity/act_113.png' WHERE name = '주간의 방랑자' AND type = 'activity';
UPDATE public.badges SET image_url = '/badges/activity/act_114.png' WHERE name = '일주일의 유산' AND type = 'activity';
UPDATE public.badges SET image_url = '/badges/activity/act_115.png' WHERE name = '1월: 혹한의 도전자' AND type = 'activity';
UPDATE public.badges SET image_url = '/badges/activity/act_116.png' WHERE name = '2월: 해빙의 발자국' AND type = 'activity';
UPDATE public.badges SET image_url = '/badges/activity/act_117.png' WHERE name = '3월: 새싹의 파수꾼' AND type = 'activity';
UPDATE public.badges SET image_url = '/badges/activity/act_118.png' WHERE name = '4월: 벚꽃의 방랑자' AND type = 'activity';
UPDATE public.badges SET image_url = '/badges/activity/act_119.png' WHERE name = '5월: 푸른 바람의 기수' AND type = 'activity';
UPDATE public.badges SET image_url = '/badges/activity/act_120.png' WHERE name = '6월: 초여름의 전령' AND type = 'activity';
UPDATE public.badges SET image_url = '/badges/activity/act_121.png' WHERE name = '7월: 폭염의 투사' AND type = 'activity';
UPDATE public.badges SET image_url = '/badges/activity/act_122.png' WHERE name = '8월: 열대야의 그림자' AND type = 'activity';
UPDATE public.badges SET image_url = '/badges/activity/act_123.png' WHERE name = '9월: 가을비의 낭만' AND type = 'activity';
UPDATE public.badges SET image_url = '/badges/activity/act_124.png' WHERE name = '10월: 단풍의 추적자' AND type = 'activity';
UPDATE public.badges SET image_url = '/badges/activity/act_125.png' WHERE name = '11월: 낙엽의 순례자' AND type = 'activity';
UPDATE public.badges SET image_url = '/badges/activity/act_126.png' WHERE name = '12월: 연말의 마에스트로' AND type = 'activity';
UPDATE public.badges SET image_url = '/badges/activity/act_127.png' WHERE name = '봄바람의 추적자' AND type = 'activity';
UPDATE public.badges SET image_url = '/badges/activity/act_128.png' WHERE name = '여름비의 무희' AND type = 'activity';
UPDATE public.badges SET image_url = '/badges/activity/act_129.png' WHERE name = '가을 단풍의 방랑자' AND type = 'activity';
UPDATE public.badges SET image_url = '/badges/activity/act_130.png' WHERE name = '겨울눈의 파수꾼' AND type = 'activity';
UPDATE public.badges SET image_url = '/badges/activity/act_131.png' WHERE name = '새해의 각성' AND type = 'activity';
UPDATE public.badges SET image_url = '/badges/activity/act_132.png' WHERE name = '춘분의 온기' AND type = 'activity';
UPDATE public.badges SET image_url = '/badges/activity/act_133.png' WHERE name = '하지의 열정' AND type = 'activity';
UPDATE public.badges SET image_url = '/badges/activity/act_134.png' WHERE name = '추분의 고독' AND type = 'activity';
UPDATE public.badges SET image_url = '/badges/activity/act_135.png' WHERE name = '동지의 심연' AND type = 'activity';
UPDATE public.badges SET image_url = '/badges/activity/act_136.png' WHERE name = '사계절의 정복자' AND type = 'activity';
UPDATE public.badges SET image_url = '/badges/activity/act_137.png' WHERE name = '금요일의 해방' AND type = 'activity';
UPDATE public.badges SET image_url = '/badges/activity/act_138.png' WHERE name = '토요일의 열기' AND type = 'activity';
UPDATE public.badges SET image_url = '/badges/activity/act_139.png' WHERE name = '일요일의 안식' AND type = 'activity';
UPDATE public.badges SET image_url = '/badges/activity/act_140.png' WHERE name = '주말의 지배자' AND type = 'activity';
UPDATE public.badges SET image_url = '/badges/activity/act_141.png' WHERE name = '휴일의 낭만' AND type = 'activity';
UPDATE public.badges SET image_url = '/badges/activity/act_142.png' WHERE name = '불타는 주말' AND type = 'activity';
UPDATE public.badges SET image_url = '/badges/activity/act_143.png' WHERE name = '여유로운 발걸음' AND type = 'activity';
UPDATE public.badges SET image_url = '/badges/activity/act_144.png' WHERE name = '심야의 도주' AND type = 'activity';
UPDATE public.badges SET image_url = '/badges/activity/act_145.png' WHERE name = '아침의 상쾌함' AND type = 'activity';
UPDATE public.badges SET image_url = '/badges/activity/act_146.png' WHERE name = '주말의 마침표' AND type = 'activity';
