-- ============================================================
-- Migration 033: 액티비티 배지 재설계 v3.1 — 115개 체계
--
-- 변경 내용:
--   기존 600개 삭제 → 5종목 × 5속성 × 4등급 = 100개 + 신규 15개 = 115개 삽입
--
--   설계 원칙:
--   1. 첫 싱크 Common 전용 (initial_sync_done gate)
--   2. Rare 이상 = 동일 종목 다른 속성 Common 보유 필수 (크로스게이트)
--   3. 속성 다양성 우선 — 유사조건 중복 배지 제거
--   4. 종목별 실제 스포츠 코칭 지표 5개를 속성으로 사용
--
--   종목/속성 구성:
--   걷기(walking):       거리·지속·빈도·연속·야간
--   로드러닝(road_running): 거리·속도·지구력·빈도·연속
--   사이클(cycling):     거리·속도·롱라이드·등반·빈도
--   등산(hiking):        고도·거리·빈도·지속·혹한
--   트레일(trail_running): 기본(거리+고도복합)·강도·울트라·빈도·혹한
-- ============================================================

BEGIN;

-- ── 1. 기존 activity 배지 삭제 ──────────────────────────────────────────────
DELETE FROM public.user_activity_badges
  WHERE badge_id IN (SELECT id FROM public.badges WHERE type = 'activity');

DELETE FROM public.badges
  WHERE type = 'activity'
    AND id NOT IN (
      SELECT linked_badge_id FROM public.poi WHERE linked_badge_id IS NOT NULL
    );

-- ── 2. 신규 100개 배지 삽입 ─────────────────────────────────────────────────
INSERT INTO public.badges
  (name, description, type, rarity, image_url, condition_json, activity_types, patch_available)
VALUES

-- ════════════════════════════════════════════════════════
-- 🚶 걷기 (walking) — 5속성 × 4등급 = 20개
-- ════════════════════════════════════════════════════════

-- W1 거리: 동네 산책러 (distance_km 누적)
  ('동네 산책러',
   '5km 누적. 섬데이 골목이 당신의 발걸음을 기억하기 시작합니다.',
   'activity', 'common', '/badges/activity-placeholder.png',
   '{"activity_type":"walking","distance_km":5.0}'::jsonb,
   '{walking}', false),
  ('동네 산책러',
   '30km 누적. 그루터기 살롱에서 당신의 이름이 처음 오르내립니다.',
   'activity', 'rare', '/badges/activity-placeholder.png',
   '{"activity_type":"walking","distance_km":30.0,"prerequisite_badge_names":["루틴의 수호자","작심삼일의 파괴자"]}'::jsonb,
   '{walking}', false),
  ('동네 산책러',
   '100km. 블랙 트랙의 지도에 당신의 동선이 새겨집니다.',
   'activity', 'legendary', '/badges/activity-placeholder.png',
   '{"activity_type":"walking","distance_km":100.0,"prerequisite_badge_names":["루틴의 수호자","작심삼일의 파괴자"]}'::jsonb,
   '{walking}', false),
  ('동네 산책러',
   '300km. 화이트 룸 진입 코드 확인 완료.',
   'activity', 'mythic', '/badges/activity-placeholder.png',
   '{"activity_type":"walking","distance_km":300.0,"prerequisite_badge_names":["루틴의 수호자","작심삼일의 파괴자"]}'::jsonb,
   '{walking}', false),

-- W2 지속: 산책의 명상가 (duration_minutes 단일 활동 최대)
  ('산책의 명상가',
   '30분 걷기 완주. 섬데이의 리듬을 처음 느낍니다.',
   'activity', 'common', '/badges/activity-placeholder.png',
   '{"activity_type":"walking","duration_minutes":30}'::jsonb,
   '{walking}', false),
  ('산책의 명상가',
   '한 시간 걷기. 그루터기 살롱이 조용히 박수를 보냅니다.',
   'activity', 'rare', '/badges/activity-placeholder.png',
   '{"activity_type":"walking","duration_minutes":60,"prerequisite_badge_names":["동네 산책러","밤의 보행자"]}'::jsonb,
   '{walking}', false),
  ('산책의 명상가',
   '90분 산책. 블랙 트랙의 명상가로 기록됩니다.',
   'activity', 'legendary', '/badges/activity-placeholder.png',
   '{"activity_type":"walking","duration_minutes":90,"prerequisite_badge_names":["동네 산책러","밤의 보행자"]}'::jsonb,
   '{walking}', false),
  ('산책의 명상가',
   '두 시간 걷기. 화이트 룸도 이 고요함을 존중합니다.',
   'activity', 'mythic', '/badges/activity-placeholder.png',
   '{"activity_type":"walking","duration_minutes":120,"prerequisite_badge_names":["동네 산책러","밤의 보행자"]}'::jsonb,
   '{walking}', false),

-- W3 빈도: 루틴의 수호자 (weekly_count)
  ('루틴의 수호자',
   '이번 주 3번 걷기 달성. 섬데이의 리듬과 발을 맞춥니다.',
   'activity', 'common', '/badges/activity-placeholder.png',
   '{"activity_type":"walking","weekly_count":3}'::jsonb,
   '{walking}', false),
  ('루틴의 수호자',
   '주 4회 달성. 그루터기 살롱이 당신의 신발 소리를 기다립니다.',
   'activity', 'rare', '/badges/activity-placeholder.png',
   '{"activity_type":"walking","weekly_count":4,"prerequisite_badge_names":["동네 산책러","산책의 명상가"]}'::jsonb,
   '{walking}', false),
  ('루틴의 수호자',
   '주 5회. 블랙 트랙이 당신의 루틴을 전설로 새깁니다.',
   'activity', 'legendary', '/badges/activity-placeholder.png',
   '{"activity_type":"walking","weekly_count":5,"prerequisite_badge_names":["동네 산책러","산책의 명상가"]}'::jsonb,
   '{walking}', false),
  ('루틴의 수호자',
   '매일 걷기. 화이트 룸은 쉬지 않는 자에게 문을 엽니다.',
   'activity', 'mythic', '/badges/activity-placeholder.png',
   '{"activity_type":"walking","weekly_count":7,"prerequisite_badge_names":["동네 산책러","산책의 명상가"]}'::jsonb,
   '{walking}', false),

-- W4 연속: 작심삼일의 파괴자 (streak_days)
  ('작심삼일의 파괴자',
   '3일 연속 걷기. 섬데이 결계의 첫 균열.',
   'activity', 'common', '/badges/activity-placeholder.png',
   '{"activity_type":"walking","streak_days":3}'::jsonb,
   '{walking}', false),
  ('작심삼일의 파괴자',
   '7일 연속. 그루터기 살롱이 당신의 연속 기록을 게시합니다.',
   'activity', 'rare', '/badges/activity-placeholder.png',
   '{"activity_type":"walking","streak_days":7,"prerequisite_badge_names":["루틴의 수호자","동네 산책러"]}'::jsonb,
   '{walking}', false),
  ('작심삼일의 파괴자',
   '14일 연속. 블랙 트랙이 작심삼일의 파괴자를 기억합니다.',
   'activity', 'legendary', '/badges/activity-placeholder.png',
   '{"activity_type":"walking","streak_days":14,"prerequisite_badge_names":["루틴의 수호자","동네 산책러"]}'::jsonb,
   '{walking}', false),
  ('작심삼일의 파괴자',
   '30일 연속. 화이트 룸은 멈추지 않는 자에게만 열립니다.',
   'activity', 'mythic', '/badges/activity-placeholder.png',
   '{"activity_type":"walking","streak_days":30,"prerequisite_badge_names":["루틴의 수호자","동네 산책러"]}'::jsonb,
   '{walking}', false),

-- W5 야간: 밤의 보행자 (time_range 22:00~05:00 + duration_minutes 복합)
  ('밤의 보행자',
   '밤 10시 이후 20분 걷기. 섬데이의 어둠 속에서 발자국이 빛납니다.',
   'activity', 'common', '/badges/activity-placeholder.png',
   '{"activity_type":"walking","time_range":{"start":"22:00","end":"05:00"},"duration_minutes":20}'::jsonb,
   '{walking}', false),
  ('밤의 보행자',
   '야간 45분 걷기. 그루터기 살롱의 불빛이 당신을 맞습니다.',
   'activity', 'rare', '/badges/activity-placeholder.png',
   '{"activity_type":"walking","time_range":{"start":"22:00","end":"05:00"},"duration_minutes":45,"prerequisite_badge_names":["동네 산책러","작심삼일의 파괴자"]}'::jsonb,
   '{walking}', false),
  ('밤의 보행자',
   '야간 한 시간 걷기. 블랙 트랙의 밤 구역에서 당신의 이름이 불립니다.',
   'activity', 'legendary', '/badges/activity-placeholder.png',
   '{"activity_type":"walking","time_range":{"start":"22:00","end":"05:00"},"duration_minutes":60,"prerequisite_badge_names":["동네 산책러","작심삼일의 파괴자"]}'::jsonb,
   '{walking}', false),
  ('밤의 보행자',
   '야간 90분. 화이트 룸은 밤을 지배하는 자를 기억합니다.',
   'activity', 'mythic', '/badges/activity-placeholder.png',
   '{"activity_type":"walking","time_range":{"start":"22:00","end":"05:00"},"duration_minutes":90,"prerequisite_badge_names":["동네 산책러","작심삼일의 파괴자"]}'::jsonb,
   '{walking}', false),

-- ════════════════════════════════════════════════════════
-- 🏃 로드러닝 (road_running) — 5속성 × 4등급 = 20개
-- ════════════════════════════════════════════════════════

-- R1 거리: 첫 숨결 (distance_km 누적)
  ('첫 숨결',
   '3km 달리기. 섬데이 아스팔트에 첫 숨결이 맺힙니다.',
   'activity', 'common', '/badges/activity-placeholder.png',
   '{"activity_type":"road_running","distance_km":3.0}'::jsonb,
   '{road_running}', false),
  ('첫 숨결',
   '20km 누적. 그루터기 살롱에서 당신의 페이스를 논합니다.',
   'activity', 'rare', '/badges/activity-placeholder.png',
   '{"activity_type":"road_running","distance_km":20.0,"prerequisite_badge_names":["리듬의 발견","달리기의 루틴"]}'::jsonb,
   '{road_running}', false),
  ('첫 숨결',
   '60km. 블랙 트랙의 전설들이 당신의 폐활량을 인정합니다.',
   'activity', 'legendary', '/badges/activity-placeholder.png',
   '{"activity_type":"road_running","distance_km":60.0,"prerequisite_badge_names":["리듬의 발견","달리기의 루틴"]}'::jsonb,
   '{road_running}', false),
  ('첫 숨결',
   '150km. 화이트 룸 진입 코드 확인 완료.',
   'activity', 'mythic', '/badges/activity-placeholder.png',
   '{"activity_type":"road_running","distance_km":150.0,"prerequisite_badge_names":["리듬의 발견","달리기의 루틴"]}'::jsonb,
   '{road_running}', false),

-- R2 속도: 리듬의 발견 (min_speed_kmh 단일 활동 최고 평균속도)
  ('리듬의 발견',
   '평균 시속 7km. 섬데이 아스팔트가 당신의 리듬을 감지합니다.',
   'activity', 'common', '/badges/activity-placeholder.png',
   '{"activity_type":"road_running","min_speed_kmh":7.0}'::jsonb,
   '{road_running}', false),
  ('리듬의 발견',
   '시속 9km 돌파. 그루터기 살롱이 당신의 스텝을 주목합니다.',
   'activity', 'rare', '/badges/activity-placeholder.png',
   '{"activity_type":"road_running","min_speed_kmh":9.0,"prerequisite_badge_names":["첫 숨결","달리기의 루틴"]}'::jsonb,
   '{road_running}', false),
  ('리듬의 발견',
   '시속 11km. 블랙 트랙의 속도 신봉자들이 고개를 끄덕입니다.',
   'activity', 'legendary', '/badges/activity-placeholder.png',
   '{"activity_type":"road_running","min_speed_kmh":11.0,"prerequisite_badge_names":["첫 숨결","달리기의 루틴"]}'::jsonb,
   '{road_running}', false),
  ('리듬의 발견',
   '시속 13km. 화이트 룸의 속도 코드를 해독했습니다.',
   'activity', 'mythic', '/badges/activity-placeholder.png',
   '{"activity_type":"road_running","min_speed_kmh":13.0,"prerequisite_badge_names":["첫 숨결","달리기의 루틴"]}'::jsonb,
   '{road_running}', false),

-- R3 지구력: 지구력의 전사 (duration_minutes 단일 활동 최대)
  ('지구력의 전사',
   '30분 달리기. 섬데이 결계에 첫 지구력의 증거가 새겨집니다.',
   'activity', 'common', '/badges/activity-placeholder.png',
   '{"activity_type":"road_running","duration_minutes":30}'::jsonb,
   '{road_running}', false),
  ('지구력의 전사',
   '한 시간 달리기. 그루터기 살롱이 당신의 페이스를 주시합니다.',
   'activity', 'rare', '/badges/activity-placeholder.png',
   '{"activity_type":"road_running","duration_minutes":60,"prerequisite_badge_names":["첫 숨결","리듬의 발견"]}'::jsonb,
   '{road_running}', false),
  ('지구력의 전사',
   '90분 레이스. 블랙 트랙의 전사 명단에 이름이 오릅니다.',
   'activity', 'legendary', '/badges/activity-placeholder.png',
   '{"activity_type":"road_running","duration_minutes":90,"prerequisite_badge_names":["첫 숨결","리듬의 발견"]}'::jsonb,
   '{road_running}', false),
  ('지구력의 전사',
   '두 시간 달리기. 화이트 룸의 지구력 코드를 획득했습니다.',
   'activity', 'mythic', '/badges/activity-placeholder.png',
   '{"activity_type":"road_running","duration_minutes":120,"prerequisite_badge_names":["첫 숨결","리듬의 발견"]}'::jsonb,
   '{road_running}', false),

-- R4 빈도: 달리기의 루틴 (weekly_count)
  ('달리기의 루틴',
   '이번 주 2번 달리기. 섬데이의 리듬이 당신에게 스며듭니다.',
   'activity', 'common', '/badges/activity-placeholder.png',
   '{"activity_type":"road_running","weekly_count":2}'::jsonb,
   '{road_running}', false),
  ('달리기의 루틴',
   '주 3회 달성. 그루터기 살롱의 달리기 명단에 등록됩니다.',
   'activity', 'rare', '/badges/activity-placeholder.png',
   '{"activity_type":"road_running","weekly_count":3,"prerequisite_badge_names":["첫 숨결","지구력의 전사"]}'::jsonb,
   '{road_running}', false),
  ('달리기의 루틴',
   '주 4회. 블랙 트랙이 당신의 루틴을 전설급으로 기록합니다.',
   'activity', 'legendary', '/badges/activity-placeholder.png',
   '{"activity_type":"road_running","weekly_count":4,"prerequisite_badge_names":["첫 숨결","지구력의 전사"]}'::jsonb,
   '{road_running}', false),
  ('달리기의 루틴',
   '주 5회 달리기. 화이트 룸은 달리는 자에게 문을 엽니다.',
   'activity', 'mythic', '/badges/activity-placeholder.png',
   '{"activity_type":"road_running","weekly_count":5,"prerequisite_badge_names":["첫 숨결","지구력의 전사"]}'::jsonb,
   '{road_running}', false),

-- R5 연속: 달리기의 연결 (streak_days)
  ('달리기의 연결',
   '3일 연속 달리기. 섬데이 결계에 균열이 시작됩니다.',
   'activity', 'common', '/badges/activity-placeholder.png',
   '{"activity_type":"road_running","streak_days":3}'::jsonb,
   '{road_running}', false),
  ('달리기의 연결',
   '7일 연속. 그루터기 살롱이 당신의 연속 기록을 공지합니다.',
   'activity', 'rare', '/badges/activity-placeholder.png',
   '{"activity_type":"road_running","streak_days":7,"prerequisite_badge_names":["달리기의 루틴","첫 숨결"]}'::jsonb,
   '{road_running}', false),
  ('달리기의 연결',
   '14일 연속 달리기. 블랙 트랙의 스트릭 보드에 이름이 새겨집니다.',
   'activity', 'legendary', '/badges/activity-placeholder.png',
   '{"activity_type":"road_running","streak_days":14,"prerequisite_badge_names":["달리기의 루틴","첫 숨결"]}'::jsonb,
   '{road_running}', false),
  ('달리기의 연결',
   '21일 연속. 화이트 룸은 멈추지 않는 달리기를 기억합니다.',
   'activity', 'mythic', '/badges/activity-placeholder.png',
   '{"activity_type":"road_running","streak_days":21,"prerequisite_badge_names":["달리기의 루틴","첫 숨결"]}'::jsonb,
   '{road_running}', false),

-- ════════════════════════════════════════════════════════
-- 🚴 사이클링 (cycling) — 5속성 × 4등급 = 20개
-- ════════════════════════════════════════════════════════

-- C1 거리: 두 바퀴의 시작 (distance_km 누적)
  ('두 바퀴의 시작',
   '10km 라이딩. 섬데이 아스팔트가 두 바퀴의 첫 신호를 감지합니다.',
   'activity', 'common', '/badges/activity-placeholder.png',
   '{"activity_type":"cycling","distance_km":10.0}'::jsonb,
   '{cycling}', false),
  ('두 바퀴의 시작',
   '50km 누적. 그루터기 살롱에서 당신의 페달 소리를 기다립니다.',
   'activity', 'rare', '/badges/activity-placeholder.png',
   '{"activity_type":"cycling","distance_km":50.0,"prerequisite_badge_names":["언덕의 도전자","장거리 항속"]}'::jsonb,
   '{cycling}', false),
  ('두 바퀴의 시작',
   '150km. 블랙 트랙의 페달 연대가 당신을 맞이합니다.',
   'activity', 'legendary', '/badges/activity-placeholder.png',
   '{"activity_type":"cycling","distance_km":150.0,"prerequisite_badge_names":["언덕의 도전자","장거리 항속"]}'::jsonb,
   '{cycling}', false),
  ('두 바퀴의 시작',
   '400km. 화이트 룸 두 바퀴 진입 코드 확인 완료.',
   'activity', 'mythic', '/badges/activity-placeholder.png',
   '{"activity_type":"cycling","distance_km":400.0,"prerequisite_badge_names":["언덕의 도전자","장거리 항속"]}'::jsonb,
   '{cycling}', false),

-- C2 속도: 페달의 리듬 (min_speed_kmh 단일 활동 최고 평균속도)
  ('페달의 리듬',
   '시속 15km. 섬데이 도로가 당신의 케이던스를 인식합니다.',
   'activity', 'common', '/badges/activity-placeholder.png',
   '{"activity_type":"cycling","min_speed_kmh":15.0}'::jsonb,
   '{cycling}', false),
  ('페달의 리듬',
   '시속 20km 돌파. 그루터기 살롱이 당신의 속도를 주목합니다.',
   'activity', 'rare', '/badges/activity-placeholder.png',
   '{"activity_type":"cycling","min_speed_kmh":20.0,"prerequisite_badge_names":["두 바퀴의 시작","장거리 항속"]}'::jsonb,
   '{cycling}', false),
  ('페달의 리듬',
   '시속 25km. 블랙 트랙 라이더들이 당신에게 길을 비킵니다.',
   'activity', 'legendary', '/badges/activity-placeholder.png',
   '{"activity_type":"cycling","min_speed_kmh":25.0,"prerequisite_badge_names":["두 바퀴의 시작","장거리 항속"]}'::jsonb,
   '{cycling}', false),
  ('페달의 리듬',
   '시속 30km. 화이트 룸의 스피드 코드를 해독했습니다.',
   'activity', 'mythic', '/badges/activity-placeholder.png',
   '{"activity_type":"cycling","min_speed_kmh":30.0,"prerequisite_badge_names":["두 바퀴의 시작","장거리 항속"]}'::jsonb,
   '{cycling}', false),

-- C3 롱라이드: 장거리 항속 (duration_minutes 단일 활동 최대)
  ('장거리 항속',
   '한 시간 라이딩. 섬데이 도로가 당신의 항속을 처음 기억합니다.',
   'activity', 'common', '/badges/activity-placeholder.png',
   '{"activity_type":"cycling","duration_minutes":60}'::jsonb,
   '{cycling}', false),
  ('장거리 항속',
   '두 시간 항속. 그루터기 살롱이 당신의 지구력에 주목합니다.',
   'activity', 'rare', '/badges/activity-placeholder.png',
   '{"activity_type":"cycling","duration_minutes":120,"prerequisite_badge_names":["두 바퀴의 시작","페달의 리듬"]}'::jsonb,
   '{cycling}', false),
  ('장거리 항속',
   '세 시간 라이딩. 블랙 트랙의 롱라이드 명단에 이름이 오릅니다.',
   'activity', 'legendary', '/badges/activity-placeholder.png',
   '{"activity_type":"cycling","duration_minutes":180,"prerequisite_badge_names":["두 바퀴의 시작","페달의 리듬"]}'::jsonb,
   '{cycling}', false),
  ('장거리 항속',
   '네 시간 항속. 화이트 룸은 끝까지 달리는 페달을 기억합니다.',
   'activity', 'mythic', '/badges/activity-placeholder.png',
   '{"activity_type":"cycling","duration_minutes":240,"prerequisite_badge_names":["두 바퀴의 시작","페달의 리듬"]}'::jsonb,
   '{cycling}', false),

-- C4 등반: 언덕의 도전자 (elevation_gain_m 누적)
  ('언덕의 도전자',
   '고도 100m 등반. 섬데이의 첫 언덕이 당신 앞에 무릎 꿇습니다.',
   'activity', 'common', '/badges/activity-placeholder.png',
   '{"activity_type":"cycling","elevation_gain_m":100.0}'::jsonb,
   '{cycling}', false),
  ('언덕의 도전자',
   '500m 누적 등반. 그루터기 살롱이 당신의 클라이밍을 인정합니다.',
   'activity', 'rare', '/badges/activity-placeholder.png',
   '{"activity_type":"cycling","elevation_gain_m":500.0,"prerequisite_badge_names":["두 바퀴의 시작","장거리 항속"]}'::jsonb,
   '{cycling}', false),
  ('언덕의 도전자',
   '1500m. 블랙 트랙의 등반 전설 명단에 이름이 올라갑니다.',
   'activity', 'legendary', '/badges/activity-placeholder.png',
   '{"activity_type":"cycling","elevation_gain_m":1500.0,"prerequisite_badge_names":["두 바퀴의 시작","장거리 항속"]}'::jsonb,
   '{cycling}', false),
  ('언덕의 도전자',
   '5000m 등반. 화이트 룸은 언덕을 정복한 자에게 열립니다.',
   'activity', 'mythic', '/badges/activity-placeholder.png',
   '{"activity_type":"cycling","elevation_gain_m":5000.0,"prerequisite_badge_names":["두 바퀴의 시작","장거리 항속"]}'::jsonb,
   '{cycling}', false),

-- C5 빈도: 사이클 루틴 (weekly_count)
  ('사이클 루틴',
   '이번 주 2번 라이딩. 섬데이 도로가 당신의 바퀴를 기억합니다.',
   'activity', 'common', '/badges/activity-placeholder.png',
   '{"activity_type":"cycling","weekly_count":2}'::jsonb,
   '{cycling}', false),
  ('사이클 루틴',
   '주 3회 달성. 그루터기 살롱의 라이더 명단에 등록됩니다.',
   'activity', 'rare', '/badges/activity-placeholder.png',
   '{"activity_type":"cycling","weekly_count":3,"prerequisite_badge_names":["두 바퀴의 시작","언덕의 도전자"]}'::jsonb,
   '{cycling}', false),
  ('사이클 루틴',
   '주 4회. 블랙 트랙이 당신의 사이클 루틴을 전설로 새깁니다.',
   'activity', 'legendary', '/badges/activity-placeholder.png',
   '{"activity_type":"cycling","weekly_count":4,"prerequisite_badge_names":["두 바퀴의 시작","언덕의 도전자"]}'::jsonb,
   '{cycling}', false),
  ('사이클 루틴',
   '주 5회 라이딩. 화이트 룸은 쉬지 않는 페달을 기다립니다.',
   'activity', 'mythic', '/badges/activity-placeholder.png',
   '{"activity_type":"cycling","weekly_count":5,"prerequisite_badge_names":["두 바퀴의 시작","언덕의 도전자"]}'::jsonb,
   '{cycling}', false),

-- ════════════════════════════════════════════════════════
-- ⛰️ 등산 (hiking) — 5속성 × 4등급 = 20개
-- ════════════════════════════════════════════════════════

-- H1 고도: 첫 고도 (elevation_gain_m 누적)
  ('첫 고도',
   '고도 200m 등반. 섬데이 산자락에 첫 발자국이 새겨집니다.',
   'activity', 'common', '/badges/activity-placeholder.png',
   '{"activity_type":"hiking","elevation_gain_m":200.0}'::jsonb,
   '{hiking}', false),
  ('첫 고도',
   '800m 누적. 그루터기 살롱이 당신의 등반 기록을 게시합니다.',
   'activity', 'rare', '/badges/activity-placeholder.png',
   '{"activity_type":"hiking","elevation_gain_m":800.0,"prerequisite_badge_names":["산자락의 첫발","주말 등산가"]}'::jsonb,
   '{hiking}', false),
  ('첫 고도',
   '2000m. 블랙 트랙의 산악 명단에 당신의 이름이 오릅니다.',
   'activity', 'legendary', '/badges/activity-placeholder.png',
   '{"activity_type":"hiking","elevation_gain_m":2000.0,"prerequisite_badge_names":["산자락의 첫발","주말 등산가"]}'::jsonb,
   '{hiking}', false),
  ('첫 고도',
   '6000m. 화이트 룸 고도 진입 코드 확인 완료.',
   'activity', 'mythic', '/badges/activity-placeholder.png',
   '{"activity_type":"hiking","elevation_gain_m":6000.0,"prerequisite_badge_names":["산자락의 첫발","주말 등산가"]}'::jsonb,
   '{hiking}', false),

-- H2 거리: 산자락의 첫발 (distance_km 누적)
  ('산자락의 첫발',
   '3km 산행. 섬데이 능선이 당신의 첫발을 기억합니다.',
   'activity', 'common', '/badges/activity-placeholder.png',
   '{"activity_type":"hiking","distance_km":3.0}'::jsonb,
   '{hiking}', false),
  ('산자락의 첫발',
   '10km 종주. 그루터기 살롱이 당신의 산행 거리를 주목합니다.',
   'activity', 'rare', '/badges/activity-placeholder.png',
   '{"activity_type":"hiking","distance_km":10.0,"prerequisite_badge_names":["첫 고도","주말 등산가"]}'::jsonb,
   '{hiking}', false),
  ('산자락의 첫발',
   '25km. 블랙 트랙의 종주자 명단에 이름이 새겨집니다.',
   'activity', 'legendary', '/badges/activity-placeholder.png',
   '{"activity_type":"hiking","distance_km":25.0,"prerequisite_badge_names":["첫 고도","주말 등산가"]}'::jsonb,
   '{hiking}', false),
  ('산자락의 첫발',
   '60km 종주. 화이트 룸은 산을 정복한 자에게 열립니다.',
   'activity', 'mythic', '/badges/activity-placeholder.png',
   '{"activity_type":"hiking","distance_km":60.0,"prerequisite_badge_names":["첫 고도","주말 등산가"]}'::jsonb,
   '{hiking}', false),

-- H3 빈도: 주말 등산가 (weekly_count)
  ('주말 등산가',
   '이번 주 등산 완료. 섬데이 산자락이 당신을 기억합니다.',
   'activity', 'common', '/badges/activity-placeholder.png',
   '{"activity_type":"hiking","weekly_count":1}'::jsonb,
   '{hiking}', false),
  ('주말 등산가',
   '주 2회 등산. 그루터기 살롱이 당신의 산행 패턴을 주시합니다.',
   'activity', 'rare', '/badges/activity-placeholder.png',
   '{"activity_type":"hiking","weekly_count":2,"prerequisite_badge_names":["첫 고도","산자락의 첫발"]}'::jsonb,
   '{hiking}', false),
  ('주말 등산가',
   '주 3회. 블랙 트랙의 등산가 명단에 이름이 올라갑니다.',
   'activity', 'legendary', '/badges/activity-placeholder.png',
   '{"activity_type":"hiking","weekly_count":3,"prerequisite_badge_names":["첫 고도","산자락의 첫발"]}'::jsonb,
   '{hiking}', false),
  ('주말 등산가',
   '주 4회 등산. 화이트 룸은 산을 사랑하는 자에게 열립니다.',
   'activity', 'mythic', '/badges/activity-placeholder.png',
   '{"activity_type":"hiking","weekly_count":4,"prerequisite_badge_names":["첫 고도","산자락의 첫발"]}'::jsonb,
   '{hiking}', false),

-- H4 지속: 산행의 깊이 (duration_minutes 단일 활동 최대)
  ('산행의 깊이',
   '한 시간 산행. 섬데이 산에서 처음 깊이를 느낍니다.',
   'activity', 'common', '/badges/activity-placeholder.png',
   '{"activity_type":"hiking","duration_minutes":60}'::jsonb,
   '{hiking}', false),
  ('산행의 깊이',
   '두 시간 산행. 그루터기 살롱이 당신의 인내를 인정합니다.',
   'activity', 'rare', '/badges/activity-placeholder.png',
   '{"activity_type":"hiking","duration_minutes":120,"prerequisite_badge_names":["첫 고도","산자락의 첫발"]}'::jsonb,
   '{hiking}', false),
  ('산행의 깊이',
   '세 시간 산행. 블랙 트랙의 심산행자 명단에 이름이 새겨집니다.',
   'activity', 'legendary', '/badges/activity-placeholder.png',
   '{"activity_type":"hiking","duration_minutes":180,"prerequisite_badge_names":["첫 고도","산자락의 첫발"]}'::jsonb,
   '{hiking}', false),
  ('산행의 깊이',
   '네 시간 산행. 화이트 룸은 산의 깊이를 아는 자에게 열립니다.',
   'activity', 'mythic', '/badges/activity-placeholder.png',
   '{"activity_type":"hiking","duration_minutes":240,"prerequisite_badge_names":["첫 고도","산자락의 첫발"]}'::jsonb,
   '{hiking}', false),

-- H5 혹한: 혹한의 등반자 (temperature_max_c — 활동 중 기온 ≤ 조건값)
  ('혹한의 등반자',
   '10°C 이하 등산. 섬데이의 차가운 바람을 처음 가릅니다.',
   'activity', 'common', '/badges/activity-placeholder.png',
   '{"activity_type":"hiking","temperature_max_c":10.0}'::jsonb,
   '{hiking}', false),
  ('혹한의 등반자',
   '영하 등산. 그루터기 살롱이 당신의 혹한 도전을 기록합니다.',
   'activity', 'rare', '/badges/activity-placeholder.png',
   '{"activity_type":"hiking","temperature_max_c":0.0,"prerequisite_badge_names":["첫 고도","산자락의 첫발"]}'::jsonb,
   '{hiking}', false),
  ('혹한의 등반자',
   '-7°C 등산. 블랙 트랙의 혹한 전사 명단에 이름이 오릅니다.',
   'activity', 'legendary', '/badges/activity-placeholder.png',
   '{"activity_type":"hiking","temperature_max_c":-7.0,"prerequisite_badge_names":["첫 고도","산자락의 첫발"]}'::jsonb,
   '{hiking}', false),
  ('혹한의 등반자',
   '-15°C 등산. 화이트 룸은 얼음을 밟는 자에게만 열립니다.',
   'activity', 'mythic', '/badges/activity-placeholder.png',
   '{"activity_type":"hiking","temperature_max_c":-15.0,"prerequisite_badge_names":["첫 고도","산자락의 첫발"]}'::jsonb,
   '{hiking}', false),

-- ════════════════════════════════════════════════════════
-- 🌲 트레일러닝 (trail_running) — 5속성 × 4등급 = 20개
-- ════════════════════════════════════════════════════════

-- T1 기본: 야생의 첫발 (distance_km + elevation_gain_m 복합 — AND 조건)
  ('야생의 첫발',
   '5km+100m 트레일. 섬데이 야생 지도에 첫 경로가 새겨집니다.',
   'activity', 'common', '/badges/activity-placeholder.png',
   '{"activity_type":"trail_running","distance_km":5.0,"elevation_gain_m":100.0}'::jsonb,
   '{trail_running}', false),
  ('야생의 첫발',
   '15km+300m. 그루터기 살롱이 당신의 트레일 기록을 공지합니다.',
   'activity', 'rare', '/badges/activity-placeholder.png',
   '{"activity_type":"trail_running","distance_km":15.0,"elevation_gain_m":300.0,"prerequisite_badge_names":["수직의 도전","트레일 루틴"]}'::jsonb,
   '{trail_running}', false),
  ('야생의 첫발',
   '40km+800m. 블랙 트랙의 야생 전설 명단에 이름이 오릅니다.',
   'activity', 'legendary', '/badges/activity-placeholder.png',
   '{"activity_type":"trail_running","distance_km":40.0,"elevation_gain_m":800.0,"prerequisite_badge_names":["수직의 도전","트레일 루틴"]}'::jsonb,
   '{trail_running}', false),
  ('야생의 첫발',
   '80km+2000m. 화이트 룸 야생 코드 확인 완료.',
   'activity', 'mythic', '/badges/activity-placeholder.png',
   '{"activity_type":"trail_running","distance_km":80.0,"elevation_gain_m":2000.0,"prerequisite_badge_names":["수직의 도전","트레일 루틴"]}'::jsonb,
   '{trail_running}', false),

-- T2 강도: 수직의 도전 (elevation_gain_m 누적)
  ('수직의 도전',
   '트레일 고도 200m. 섬데이 수직 지도가 당신을 기록합니다.',
   'activity', 'common', '/badges/activity-placeholder.png',
   '{"activity_type":"trail_running","elevation_gain_m":200.0}'::jsonb,
   '{trail_running}', false),
  ('수직의 도전',
   '600m 수직 달리기. 그루터기 살롱이 당신의 오르막을 주시합니다.',
   'activity', 'rare', '/badges/activity-placeholder.png',
   '{"activity_type":"trail_running","elevation_gain_m":600.0,"prerequisite_badge_names":["야생의 첫발","트레일 루틴"]}'::jsonb,
   '{trail_running}', false),
  ('수직의 도전',
   '1500m 누적. 블랙 트랙의 수직 전사 명단에 이름이 올라갑니다.',
   'activity', 'legendary', '/badges/activity-placeholder.png',
   '{"activity_type":"trail_running","elevation_gain_m":1500.0,"prerequisite_badge_names":["야생의 첫발","트레일 루틴"]}'::jsonb,
   '{trail_running}', false),
  ('수직의 도전',
   '4000m 수직. 화이트 룸은 중력을 이긴 자에게 열립니다.',
   'activity', 'mythic', '/badges/activity-placeholder.png',
   '{"activity_type":"trail_running","elevation_gain_m":4000.0,"prerequisite_badge_names":["야생의 첫발","트레일 루틴"]}'::jsonb,
   '{trail_running}', false),

-- T3 울트라: 야생의 주자 (distance_km 누적)
  ('야생의 주자',
   '트레일 10km. 섬데이 야생 트랙에 당신의 발자국이 찍힙니다.',
   'activity', 'common', '/badges/activity-placeholder.png',
   '{"activity_type":"trail_running","distance_km":10.0}'::jsonb,
   '{trail_running}', false),
  ('야생의 주자',
   '30km 트레일. 그루터기 살롱이 야생의 주자를 주목합니다.',
   'activity', 'rare', '/badges/activity-placeholder.png',
   '{"activity_type":"trail_running","distance_km":30.0,"prerequisite_badge_names":["야생의 첫발","수직의 도전"]}'::jsonb,
   '{trail_running}', false),
  ('야생의 주자',
   '60km. 블랙 트랙의 울트라 주자 명단에 이름이 새겨집니다.',
   'activity', 'legendary', '/badges/activity-placeholder.png',
   '{"activity_type":"trail_running","distance_km":60.0,"prerequisite_badge_names":["야생의 첫발","수직의 도전"]}'::jsonb,
   '{trail_running}', false),
  ('야생의 주자',
   '100km. 화이트 룸은 야생을 완주한 자에게만 열립니다.',
   'activity', 'mythic', '/badges/activity-placeholder.png',
   '{"activity_type":"trail_running","distance_km":100.0,"prerequisite_badge_names":["야생의 첫발","수직의 도전"]}'::jsonb,
   '{trail_running}', false),

-- T4 빈도: 트레일 루틴 (weekly_count)
  ('트레일 루틴',
   '이번 주 트레일러닝 완료. 섬데이 야생이 당신을 기억합니다.',
   'activity', 'common', '/badges/activity-placeholder.png',
   '{"activity_type":"trail_running","weekly_count":1}'::jsonb,
   '{trail_running}', false),
  ('트레일 루틴',
   '주 2회 트레일. 그루터기 살롱이 당신의 야생 루틴을 주목합니다.',
   'activity', 'rare', '/badges/activity-placeholder.png',
   '{"activity_type":"trail_running","weekly_count":2,"prerequisite_badge_names":["야생의 첫발","야생의 주자"]}'::jsonb,
   '{trail_running}', false),
  ('트레일 루틴',
   '주 3회 트레일. 블랙 트랙의 야생 루티너 명단에 오릅니다.',
   'activity', 'legendary', '/badges/activity-placeholder.png',
   '{"activity_type":"trail_running","weekly_count":3,"prerequisite_badge_names":["야생의 첫발","야생의 주자"]}'::jsonb,
   '{trail_running}', false),
  ('트레일 루틴',
   '주 4회 트레일. 화이트 룸은 야생을 사랑하는 자에게 열립니다.',
   'activity', 'mythic', '/badges/activity-placeholder.png',
   '{"activity_type":"trail_running","weekly_count":4,"prerequisite_badge_names":["야생의 첫발","야생의 주자"]}'::jsonb,
   '{trail_running}', false),

-- T5 혹한: 혹한의 트레일러 (temperature_max_c — 활동 중 기온 ≤ 조건값)
  ('혹한의 트레일러',
   '10°C 이하 트레일. 섬데이 야생의 한기를 가르며 달립니다.',
   'activity', 'common', '/badges/activity-placeholder.png',
   '{"activity_type":"trail_running","temperature_max_c":10.0}'::jsonb,
   '{trail_running}', false),
  ('혹한의 트레일러',
   '영하 트레일. 그루터기 살롱이 당신의 혹한 질주를 기록합니다.',
   'activity', 'rare', '/badges/activity-placeholder.png',
   '{"activity_type":"trail_running","temperature_max_c":0.0,"prerequisite_badge_names":["야생의 첫발","수직의 도전"]}'::jsonb,
   '{trail_running}', false),
  ('혹한의 트레일러',
   '-7°C 트레일. 블랙 트랙의 혹한 주자 명단에 오릅니다.',
   'activity', 'legendary', '/badges/activity-placeholder.png',
   '{"activity_type":"trail_running","temperature_max_c":-7.0,"prerequisite_badge_names":["야생의 첫발","수직의 도전"]}'::jsonb,
   '{trail_running}', false),
  ('혹한의 트레일러',
   '-15°C 트레일. 화이트 룸은 얼어붙은 야생을 달리는 자에게 열립니다.',
   'activity', 'mythic', '/badges/activity-placeholder.png',
   '{"activity_type":"trail_running","temperature_max_c":-15.0,"prerequisite_badge_names":["야생의 첫발","수직의 도전"]}'::jsonb,
   '{trail_running}', false);

-- ── 3. 신규 15개 배지 삽입 (v3.1 — 카테고리 1·2·3) ──────────────────────────
INSERT INTO public.badges
  (name, description, type, rarity, image_url, condition_json, activity_types, patch_available)
VALUES

-- ════════════════════════════════════════════════════════
-- 🚶 걷기 — W6·W7·W8
-- ════════════════════════════════════════════════════════

-- W6 이달의 산책왕 (monthly_km — 카테고리 1 고난이도)
  ('이달의 산책왕',
   '이달 50km 걷기. 섬데이 골목이 당신의 이달 동선을 촘촘히 기억합니다.',
   'activity', 'common', '/badges/activity-placeholder.png',
   '{"activity_type":"walking","monthly_km":50.0}'::jsonb,
   '{walking}', false),
  ('이달의 산책왕',
   '이달 100km. 그루터기 살롱이 이달의 발걸음 총량을 집계합니다.',
   'activity', 'rare', '/badges/activity-placeholder.png',
   '{"activity_type":"walking","monthly_km":100.0,"prerequisite_badge_names":["동네 산책러","루틴의 수호자"]}'::jsonb,
   '{walking}', false),
  ('이달의 산책왕',
   '이달 150km. 블랙 트랙이 이달의 산책왕으로 기록합니다.',
   'activity', 'legendary', '/badges/activity-placeholder.png',
   '{"activity_type":"walking","monthly_km":150.0,"prerequisite_badge_names":["동네 산책러","루틴의 수호자"]}'::jsonb,
   '{walking}', false),
  ('이달의 산책왕',
   '이달 250km. 화이트 룸은 매달 멈추지 않는 자를 기억합니다.',
   'activity', 'mythic', '/badges/activity-placeholder.png',
   '{"activity_type":"walking","monthly_km":250.0,"prerequisite_badge_names":["동네 산책러","루틴의 수호자"]}'::jsonb,
   '{walking}', false),

-- W7 새벽 루틴 마스터 (time_range 05:00~08:00 + weekly_count — 카테고리 2 복합속성)
  ('새벽 루틴 마스터',
   '새벽 5~8시 걷기 주 2회. 섬데이의 고요함이 당신 것이 됩니다.',
   'activity', 'common', '/badges/activity-placeholder.png',
   '{"activity_type":"walking","time_range":{"start":"05:00","end":"08:00"},"weekly_count":2}'::jsonb,
   '{walking}', false),
  ('새벽 루틴 마스터',
   '새벽 주 3회. 그루터기 살롱은 아직 문도 열지 않았는데 당신의 발소리가 들립니다.',
   'activity', 'rare', '/badges/activity-placeholder.png',
   '{"activity_type":"walking","time_range":{"start":"05:00","end":"08:00"},"weekly_count":3,"prerequisite_badge_names":["루틴의 수호자","밤의 보행자"]}'::jsonb,
   '{walking}', false),
  ('새벽 루틴 마스터',
   '새벽 주 4회. 블랙 트랙이 동트기 전부터 당신을 기다립니다.',
   'activity', 'legendary', '/badges/activity-placeholder.png',
   '{"activity_type":"walking","time_range":{"start":"05:00","end":"08:00"},"weekly_count":4,"prerequisite_badge_names":["루틴의 수호자","밤의 보행자"]}'::jsonb,
   '{walking}', false),
  ('새벽 루틴 마스터',
   '새벽 주 5회. 화이트 룸은 해가 뜨기 전에 문을 엽니다.',
   'activity', 'mythic', '/badges/activity-placeholder.png',
   '{"activity_type":"walking","time_range":{"start":"05:00","end":"08:00"},"weekly_count":5,"prerequisite_badge_names":["루틴의 수호자","밤의 보행자"]}'::jsonb,
   '{walking}', false),

-- W8 점심 산책러 (time_range 12:00~14:00 + weekly_count — 카테고리 3 리텐션)
  ('점심 산책러',
   '낮 12~2시 걷기 첫 발걸음. 섬데이 낮의 리듬을 발견합니다.',
   'activity', 'common', '/badges/activity-placeholder.png',
   '{"activity_type":"walking","time_range":{"start":"12:00","end":"14:00"},"weekly_count":1}'::jsonb,
   '{walking}', false),
  ('점심 산책러',
   '점심 주 2회. 그루터기 살롱이 당신의 점심 발소리를 기다립니다.',
   'activity', 'rare', '/badges/activity-placeholder.png',
   '{"activity_type":"walking","time_range":{"start":"12:00","end":"14:00"},"weekly_count":2,"prerequisite_badge_names":["동네 산책러","루틴의 수호자"]}'::jsonb,
   '{walking}', false),
  ('점심 산책러',
   '점심 주 3회. 블랙 트랙의 낮 명단에 이름이 오릅니다.',
   'activity', 'legendary', '/badges/activity-placeholder.png',
   '{"activity_type":"walking","time_range":{"start":"12:00","end":"14:00"},"weekly_count":3,"prerequisite_badge_names":["동네 산책러","루틴의 수호자"]}'::jsonb,
   '{walking}', false),
  ('점심 산책러',
   '점심 매일 산책. 화이트 룸은 낮과 밤 모두를 아는 자에게 열립니다.',
   'activity', 'mythic', '/badges/activity-placeholder.png',
   '{"activity_type":"walking","time_range":{"start":"12:00","end":"14:00"},"weekly_count":5,"prerequisite_badge_names":["동네 산책러","루틴의 수호자"]}'::jsonb,
   '{walking}', false),

-- ════════════════════════════════════════════════════════
-- 🏃 로드러닝 — R6·R7·R8
-- ════════════════════════════════════════════════════════

-- R6 이달의 주자왕 (monthly_km — 카테고리 1 고난이도)
  ('이달의 주자왕',
   '이달 30km 달리기. 섬데이 아스팔트가 이달의 발자국을 집계합니다.',
   'activity', 'common', '/badges/activity-placeholder.png',
   '{"activity_type":"road_running","monthly_km":30.0}'::jsonb,
   '{road_running}', false),
  ('이달의 주자왕',
   '이달 60km. 그루터기 살롱이 이달의 러너를 주목합니다.',
   'activity', 'rare', '/badges/activity-placeholder.png',
   '{"activity_type":"road_running","monthly_km":60.0,"prerequisite_badge_names":["첫 숨결","달리기의 루틴"]}'::jsonb,
   '{road_running}', false),
  ('이달의 주자왕',
   '이달 120km. 블랙 트랙이 이달의 주자왕으로 기록합니다.',
   'activity', 'legendary', '/badges/activity-placeholder.png',
   '{"activity_type":"road_running","monthly_km":120.0,"prerequisite_badge_names":["첫 숨결","달리기의 루틴"]}'::jsonb,
   '{road_running}', false),
  ('이달의 주자왕',
   '이달 200km. 화이트 룸은 달리는 달을 사는 자에게 열립니다.',
   'activity', 'mythic', '/badges/activity-placeholder.png',
   '{"activity_type":"road_running","monthly_km":200.0,"prerequisite_badge_names":["첫 숨결","달리기의 루틴"]}'::jsonb,
   '{road_running}', false),

-- R7 스피드 엔듀러 (min_speed_kmh + duration_minutes — 카테고리 2 복합속성)
  ('스피드 엔듀러',
   '속도와 지구력의 첫 교차점. 섬데이 아스팔트가 두 면을 동시에 인식합니다.',
   'activity', 'common', '/badges/activity-placeholder.png',
   '{"activity_type":"road_running","min_speed_kmh":8.0,"duration_minutes":30}'::jsonb,
   '{road_running}', false),
  ('스피드 엔듀러',
   '빠르고 오래 달리는 자. 그루터기 살롱이 두 이력을 함께 주목합니다.',
   'activity', 'rare', '/badges/activity-placeholder.png',
   '{"activity_type":"road_running","min_speed_kmh":9.0,"duration_minutes":45,"prerequisite_badge_names":["리듬의 발견","지구력의 전사"]}'::jsonb,
   '{road_running}', false),
  ('스피드 엔듀러',
   '속도와 지구력 두 전장을 지배합니다. 블랙 트랙이 두 이름으로 기록합니다.',
   'activity', 'legendary', '/badges/activity-placeholder.png',
   '{"activity_type":"road_running","min_speed_kmh":11.0,"duration_minutes":60,"prerequisite_badge_names":["리듬의 발견","지구력의 전사"]}'::jsonb,
   '{road_running}', false),
  ('스피드 엔듀러',
   '극한 속도와 극한 지구력. 화이트 룸은 두 코드를 동시에 해독한 자에게 열립니다.',
   'activity', 'mythic', '/badges/activity-placeholder.png',
   '{"activity_type":"road_running","min_speed_kmh":13.0,"duration_minutes":90,"prerequisite_badge_names":["리듬의 발견","지구력의 전사"]}'::jsonb,
   '{road_running}', false),

-- R8 주말 파이터 (weekend_duration_hours — 카테고리 3 리텐션)
  ('주말 파이터',
   '주말 30분 달리기. 섬데이 주말 아스팔트의 첫 파이터.',
   'activity', 'common', '/badges/activity-placeholder.png',
   '{"activity_type":"road_running","weekend_duration_hours":0.5}'::jsonb,
   '{road_running}', false),
  ('주말 파이터',
   '주말 한 시간 달리기. 그루터기 살롱이 주말 파이터를 주목합니다.',
   'activity', 'rare', '/badges/activity-placeholder.png',
   '{"activity_type":"road_running","weekend_duration_hours":1.0,"prerequisite_badge_names":["첫 숨결","달리기의 루틴"]}'::jsonb,
   '{road_running}', false),
  ('주말 파이터',
   '주말 90분 레이스. 블랙 트랙의 주말 전사 명단에 오릅니다.',
   'activity', 'legendary', '/badges/activity-placeholder.png',
   '{"activity_type":"road_running","weekend_duration_hours":1.5,"prerequisite_badge_names":["첫 숨결","달리기의 루틴"]}'::jsonb,
   '{road_running}', false),
  ('주말 파이터',
   '주말 두 시간 반 달리기. 화이트 룸은 주말을 바치는 자에게 열립니다.',
   'activity', 'mythic', '/badges/activity-placeholder.png',
   '{"activity_type":"road_running","weekend_duration_hours":2.5,"prerequisite_badge_names":["첫 숨결","달리기의 루틴"]}'::jsonb,
   '{road_running}', false),

-- ════════════════════════════════════════════════════════
-- 🚴 사이클링 — C6·C7·C8
-- ════════════════════════════════════════════════════════

-- C6 이달의 그란폰도 (monthly_km — 카테고리 1 고난이도)
  ('이달의 그란폰도',
   '이달 100km 라이딩. 섬데이 도로가 이달의 페달을 기억합니다.',
   'activity', 'common', '/badges/activity-placeholder.png',
   '{"activity_type":"cycling","monthly_km":100.0}'::jsonb,
   '{cycling}', false),
  ('이달의 그란폰도',
   '이달 250km. 그루터기 살롱이 이달의 라이더를 집계합니다.',
   'activity', 'rare', '/badges/activity-placeholder.png',
   '{"activity_type":"cycling","monthly_km":250.0,"prerequisite_badge_names":["두 바퀴의 시작","사이클 루틴"]}'::jsonb,
   '{cycling}', false),
  ('이달의 그란폰도',
   '이달 500km. 블랙 트랙이 이달의 그란폰도를 기록합니다.',
   'activity', 'legendary', '/badges/activity-placeholder.png',
   '{"activity_type":"cycling","monthly_km":500.0,"prerequisite_badge_names":["두 바퀴의 시작","사이클 루틴"]}'::jsonb,
   '{cycling}', false),
  ('이달의 그란폰도',
   '이달 800km. 화이트 룸은 페달을 멈추지 않는 자에게 열립니다.',
   'activity', 'mythic', '/badges/activity-placeholder.png',
   '{"activity_type":"cycling","monthly_km":800.0,"prerequisite_badge_names":["두 바퀴의 시작","사이클 루틴"]}'::jsonb,
   '{cycling}', false),

-- C7 산악 라이더 (min_speed_kmh + elevation_gain_m — 카테고리 2 복합속성)
  ('산악 라이더',
   '속도와 고도의 첫 조합. 섬데이 도로와 언덕이 당신을 동시에 인식합니다.',
   'activity', 'common', '/badges/activity-placeholder.png',
   '{"activity_type":"cycling","min_speed_kmh":15.0,"elevation_gain_m":300.0}'::jsonb,
   '{cycling}', false),
  ('산악 라이더',
   '빠르고 높이 오르는 자. 그루터기 살롱이 두 기록을 함께 주목합니다.',
   'activity', 'rare', '/badges/activity-placeholder.png',
   '{"activity_type":"cycling","min_speed_kmh":20.0,"elevation_gain_m":1500.0,"prerequisite_badge_names":["페달의 리듬","언덕의 도전자"]}'::jsonb,
   '{cycling}', false),
  ('산악 라이더',
   '속도와 등반을 겸비한 라이더. 블랙 트랙의 산악 전설 명단에 이름이 오릅니다.',
   'activity', 'legendary', '/badges/activity-placeholder.png',
   '{"activity_type":"cycling","min_speed_kmh":25.0,"elevation_gain_m":4000.0,"prerequisite_badge_names":["페달의 리듬","언덕의 도전자"]}'::jsonb,
   '{cycling}', false),
  ('산악 라이더',
   '극한 속도와 극한 등반. 화이트 룸은 두 정점을 정복한 자에게 열립니다.',
   'activity', 'mythic', '/badges/activity-placeholder.png',
   '{"activity_type":"cycling","min_speed_kmh":30.0,"elevation_gain_m":8000.0,"prerequisite_badge_names":["페달의 리듬","언덕의 도전자"]}'::jsonb,
   '{cycling}', false),

-- C8 계절 라이더 (season:summer + season_count — 카테고리 3 리텐션)
  ('계절 라이더',
   '여름 라이딩 5회. 섬데이의 여름 도로가 당신의 바퀴를 기억합니다.',
   'activity', 'common', '/badges/activity-placeholder.png',
   '{"activity_type":"cycling","season":"summer","season_count":5}'::jsonb,
   '{cycling}', false),
  ('계절 라이더',
   '여름 10회. 그루터기 살롱이 여름의 라이더로 등록합니다.',
   'activity', 'rare', '/badges/activity-placeholder.png',
   '{"activity_type":"cycling","season":"summer","season_count":10,"prerequisite_badge_names":["두 바퀴의 시작","사이클 루틴"]}'::jsonb,
   '{cycling}', false),
  ('계절 라이더',
   '여름 20회. 블랙 트랙이 이 여름의 라이더를 전설로 새깁니다.',
   'activity', 'legendary', '/badges/activity-placeholder.png',
   '{"activity_type":"cycling","season":"summer","season_count":20,"prerequisite_badge_names":["두 바퀴의 시작","사이클 루틴"]}'::jsonb,
   '{cycling}', false),
  ('계절 라이더',
   '여름 30회. 화이트 룸은 계절을 정복한 자에게 열립니다.',
   'activity', 'mythic', '/badges/activity-placeholder.png',
   '{"activity_type":"cycling","season":"summer","season_count":30,"prerequisite_badge_names":["두 바퀴의 시작","사이클 루틴"]}'::jsonb,
   '{cycling}', false),

-- ════════════════════════════════════════════════════════
-- ⛰️ 등산 — H6·H7·H8
-- ════════════════════════════════════════════════════════

-- H6 이달의 정복자 (monthly_km — 카테고리 1 고난이도)
  ('이달의 정복자',
   '이달 20km 산행. 섬데이 산자락이 이달의 발걸음을 기억합니다.',
   'activity', 'common', '/badges/activity-placeholder.png',
   '{"activity_type":"hiking","monthly_km":20.0}'::jsonb,
   '{hiking}', false),
  ('이달의 정복자',
   '이달 40km. 그루터기 살롱이 이달의 등산가를 집계합니다.',
   'activity', 'rare', '/badges/activity-placeholder.png',
   '{"activity_type":"hiking","monthly_km":40.0,"prerequisite_badge_names":["산자락의 첫발","주말 등산가"]}'::jsonb,
   '{hiking}', false),
  ('이달의 정복자',
   '이달 80km 산행. 블랙 트랙이 이달의 정복자로 기록합니다.',
   'activity', 'legendary', '/badges/activity-placeholder.png',
   '{"activity_type":"hiking","monthly_km":80.0,"prerequisite_badge_names":["산자락의 첫발","주말 등산가"]}'::jsonb,
   '{hiking}', false),
  ('이달의 정복자',
   '이달 120km. 화이트 룸은 매달 산을 정복하는 자에게 열립니다.',
   'activity', 'mythic', '/badges/activity-placeholder.png',
   '{"activity_type":"hiking","monthly_km":120.0,"prerequisite_badge_names":["산자락의 첫발","주말 등산가"]}'::jsonb,
   '{hiking}', false),

-- H7 혹한 장정 (temperature_max_c + duration_minutes — 카테고리 2 복합속성)
  ('혹한 장정',
   '차가운 공기와 90분 산행. 섬데이 산이 두 조건을 동시에 기록합니다.',
   'activity', 'common', '/badges/activity-placeholder.png',
   '{"activity_type":"hiking","temperature_max_c":10.0,"duration_minutes":90}'::jsonb,
   '{hiking}', false),
  ('혹한 장정',
   '혹한과 장기 산행의 교차. 그루터기 살롱이 두 기록을 주목합니다.',
   'activity', 'rare', '/badges/activity-placeholder.png',
   '{"activity_type":"hiking","temperature_max_c":5.0,"duration_minutes":120,"prerequisite_badge_names":["혹한의 등반자","산행의 깊이"]}'::jsonb,
   '{hiking}', false),
  ('혹한 장정',
   '영하의 한기와 세 시간 산행. 블랙 트랙의 혹한 장정 명단에 이름이 오릅니다.',
   'activity', 'legendary', '/badges/activity-placeholder.png',
   '{"activity_type":"hiking","temperature_max_c":0.0,"duration_minutes":180,"prerequisite_badge_names":["혹한의 등반자","산행의 깊이"]}'::jsonb,
   '{hiking}', false),
  ('혹한 장정',
   '극한 혹한과 네 시간 산행. 화이트 룸은 두 극한을 동시에 정복한 자에게 열립니다.',
   'activity', 'mythic', '/badges/activity-placeholder.png',
   '{"activity_type":"hiking","temperature_max_c":-7.0,"duration_minutes":240,"prerequisite_badge_names":["혹한의 등반자","산행의 깊이"]}'::jsonb,
   '{hiking}', false),

-- H8 주말 등반자 (weekend_duration_hours — 카테고리 3 리텐션)
  ('주말 등반자',
   '주말 두 시간 산행. 섬데이 산이 주말의 첫 방문자를 기억합니다.',
   'activity', 'common', '/badges/activity-placeholder.png',
   '{"activity_type":"hiking","weekend_duration_hours":2.0}'::jsonb,
   '{hiking}', false),
  ('주말 등반자',
   '주말 네 시간 산행. 그루터기 살롱이 주말 등반자를 주목합니다.',
   'activity', 'rare', '/badges/activity-placeholder.png',
   '{"activity_type":"hiking","weekend_duration_hours":4.0,"prerequisite_badge_names":["첫 고도","산자락의 첫발"]}'::jsonb,
   '{hiking}', false),
  ('주말 등반자',
   '주말 여섯 시간 산행. 블랙 트랙의 주말 등반 명단에 이름이 오릅니다.',
   'activity', 'legendary', '/badges/activity-placeholder.png',
   '{"activity_type":"hiking","weekend_duration_hours":6.0,"prerequisite_badge_names":["첫 고도","산자락의 첫발"]}'::jsonb,
   '{hiking}', false),
  ('주말 등반자',
   '주말 여덟 시간 산행. 화이트 룸은 주말 전체를 산에 바치는 자에게 열립니다.',
   'activity', 'mythic', '/badges/activity-placeholder.png',
   '{"activity_type":"hiking","weekend_duration_hours":8.0,"prerequisite_badge_names":["첫 고도","산자락의 첫발"]}'::jsonb,
   '{hiking}', false),

-- ════════════════════════════════════════════════════════
-- 🌲 트레일러닝 — T6·T7·T8
-- ════════════════════════════════════════════════════════

-- T6 이달의 야생왕 (monthly_km — 카테고리 1 고난이도)
  ('이달의 야생왕',
   '이달 20km 트레일. 섬데이 야생 지도가 이달의 경로를 기억합니다.',
   'activity', 'common', '/badges/activity-placeholder.png',
   '{"activity_type":"trail_running","monthly_km":20.0}'::jsonb,
   '{trail_running}', false),
  ('이달의 야생왕',
   '이달 50km. 그루터기 살롱이 이달의 야생 주자를 집계합니다.',
   'activity', 'rare', '/badges/activity-placeholder.png',
   '{"activity_type":"trail_running","monthly_km":50.0,"prerequisite_badge_names":["야생의 주자","트레일 루틴"]}'::jsonb,
   '{trail_running}', false),
  ('이달의 야생왕',
   '이달 100km. 블랙 트랙이 이달의 야생왕으로 기록합니다.',
   'activity', 'legendary', '/badges/activity-placeholder.png',
   '{"activity_type":"trail_running","monthly_km":100.0,"prerequisite_badge_names":["야생의 주자","트레일 루틴"]}'::jsonb,
   '{trail_running}', false),
  ('이달의 야생왕',
   '이달 200km. 화이트 룸은 야생을 매달 달리는 자에게 열립니다.',
   'activity', 'mythic', '/badges/activity-placeholder.png',
   '{"activity_type":"trail_running","monthly_km":200.0,"prerequisite_badge_names":["야생의 주자","트레일 루틴"]}'::jsonb,
   '{trail_running}', false),

-- T7 알파인 트레일러 (elevation_gain_m + temperature_max_c — 카테고리 2 복합속성)
  ('알파인 트레일러',
   '고도와 추위의 첫 만남. 섬데이 야생이 두 조건을 동시에 인식합니다.',
   'activity', 'common', '/badges/activity-placeholder.png',
   '{"activity_type":"trail_running","elevation_gain_m":300.0,"temperature_max_c":10.0}'::jsonb,
   '{trail_running}', false),
  ('알파인 트레일러',
   '높고 차가운 트레일. 그루터기 살롱이 두 기록을 함께 주목합니다.',
   'activity', 'rare', '/badges/activity-placeholder.png',
   '{"activity_type":"trail_running","elevation_gain_m":1000.0,"temperature_max_c":5.0,"prerequisite_badge_names":["수직의 도전","혹한의 트레일러"]}'::jsonb,
   '{trail_running}', false),
  ('알파인 트레일러',
   '누적 고도와 영하 트레일. 블랙 트랙의 알파인 전사 명단에 이름이 오릅니다.',
   'activity', 'legendary', '/badges/activity-placeholder.png',
   '{"activity_type":"trail_running","elevation_gain_m":2500.0,"temperature_max_c":0.0,"prerequisite_badge_names":["수직의 도전","혹한의 트레일러"]}'::jsonb,
   '{trail_running}', false),
  ('알파인 트레일러',
   '극한 고도와 극한 혹한. 화이트 룸은 두 알파인 코드를 해독한 자에게 열립니다.',
   'activity', 'mythic', '/badges/activity-placeholder.png',
   '{"activity_type":"trail_running","elevation_gain_m":5000.0,"temperature_max_c":-5.0,"prerequisite_badge_names":["수직의 도전","혹한의 트레일러"]}'::jsonb,
   '{trail_running}', false),

-- T8 새벽 야생인 (time_range 05:00~09:00 + weekly_count — 카테고리 3 리텐션)
  ('새벽 야생인',
   '새벽 5~9시 트레일 주 1회. 섬데이 야생의 여명이 당신의 발소리를 기억합니다.',
   'activity', 'common', '/badges/activity-placeholder.png',
   '{"activity_type":"trail_running","time_range":{"start":"05:00","end":"09:00"},"weekly_count":1}'::jsonb,
   '{trail_running}', false),
  ('새벽 야생인',
   '새벽 주 2회 트레일. 그루터기 살롱이 해 뜨기 전 야생의 주자를 주목합니다.',
   'activity', 'rare', '/badges/activity-placeholder.png',
   '{"activity_type":"trail_running","time_range":{"start":"05:00","end":"09:00"},"weekly_count":2,"prerequisite_badge_names":["야생의 첫발","트레일 루틴"]}'::jsonb,
   '{trail_running}', false),
  ('새벽 야생인',
   '새벽 주 3회. 블랙 트랙이 여명의 트레일러를 전설로 새깁니다.',
   'activity', 'legendary', '/badges/activity-placeholder.png',
   '{"activity_type":"trail_running","time_range":{"start":"05:00","end":"09:00"},"weekly_count":3,"prerequisite_badge_names":["야생의 첫발","트레일 루틴"]}'::jsonb,
   '{trail_running}', false),
  ('새벽 야생인',
   '새벽 주 4회 트레일. 화이트 룸은 야생의 새벽을 지배하는 자에게 열립니다.',
   'activity', 'mythic', '/badges/activity-placeholder.png',
   '{"activity_type":"trail_running","time_range":{"start":"05:00","end":"09:00"},"weekly_count":4,"prerequisite_badge_names":["야생의 첫발","트레일 루틴"]}'::jsonb,
   '{trail_running}', false);

COMMIT;
