-- ============================================================
-- Migration 037: 전체 배지 이미지 균등 재랜덤 배정 (036 버그 수정 + 활동배지 포함)
--
-- 036의 문제:
--   UPDATE ... SET image_url = (SELECT path FROM sample_images ORDER BY random() LIMIT 1)
--   형태의 "바깥 테이블과 연관되지 않은(uncorrelated) 서브쿼리"는 PostgreSQL이
--   행마다 재실행하지 않고 쿼리 전체에서 단 한 번만 계산해(InitPlan) 모든 행에
--   동일한 결과를 재사용한다. 그 결과 무작위처럼 보이지만 실제로는 아이템배지
--   900개 전부가 같은 이미지 한 장으로 채워지는 버그가 발생했다.
--
-- 이번 수정:
--   1) row_number() 기반 셔플 매칭(JOIN)으로 실제 행별 무작위 배정 — 035에서
--      검증된 것과 동일한 패턴(스칼라 서브쿼리 대신 진짜 다대다 조인 사용).
--   2) 대상을 아이템배지(기존 036이 잘못 채운 /badges/sample/%)뿐 아니라
--      활동배지(공유 placeholder /badges/activity-placeholder.png)까지 확장.
--   3) 372장을 셔플 → 대상 배지도 셔플 → 순번으로 순환 매칭 → 372장이 거의
--      균등하게(1060행 ÷ 372장 ≈ 2~3회씩) 사용되도록 보장. 어떤 배지가 어떤
--      이미지를 받을지는 두 셔플이 모두 랜덤이라 사실상 무작위.
-- ============================================================

BEGIN;

WITH pool AS (
  SELECT path, row_number() OVER (ORDER BY random()) AS rn
  FROM (VALUES
  ('/badges/sample/s001.png'),
  ('/badges/sample/s002.png'),
  ('/badges/sample/s003.png'),
  ('/badges/sample/s004.png'),
  ('/badges/sample/s005.png'),
  ('/badges/sample/s006.png'),
  ('/badges/sample/s007.png'),
  ('/badges/sample/s008.png'),
  ('/badges/sample/s009.png'),
  ('/badges/sample/s010.png'),
  ('/badges/sample/s011.png'),
  ('/badges/sample/s012.png'),
  ('/badges/sample/s013.png'),
  ('/badges/sample/s014.png'),
  ('/badges/sample/s015.png'),
  ('/badges/sample/s016.png'),
  ('/badges/sample/s017.png'),
  ('/badges/sample/s018.png'),
  ('/badges/sample/s019.png'),
  ('/badges/sample/s020.png'),
  ('/badges/sample/s021.png'),
  ('/badges/sample/s022.png'),
  ('/badges/sample/s023.png'),
  ('/badges/sample/s024.png'),
  ('/badges/sample/s025.png'),
  ('/badges/sample/s026.png'),
  ('/badges/sample/s027.png'),
  ('/badges/sample/s028.png'),
  ('/badges/sample/s029.png'),
  ('/badges/sample/s030.png'),
  ('/badges/sample/s031.png'),
  ('/badges/sample/s032.png'),
  ('/badges/sample/s033.png'),
  ('/badges/sample/s034.png'),
  ('/badges/sample/s035.png'),
  ('/badges/sample/s036.png'),
  ('/badges/sample/s037.png'),
  ('/badges/sample/s038.png'),
  ('/badges/sample/s039.png'),
  ('/badges/sample/s040.png'),
  ('/badges/sample/s041.png'),
  ('/badges/sample/s042.png'),
  ('/badges/sample/s043.png'),
  ('/badges/sample/s044.png'),
  ('/badges/sample/s045.png'),
  ('/badges/sample/s046.png'),
  ('/badges/sample/s047.png'),
  ('/badges/sample/s048.png'),
  ('/badges/sample/s049.png'),
  ('/badges/sample/s050.png'),
  ('/badges/sample/s051.png'),
  ('/badges/sample/s052.png'),
  ('/badges/sample/s053.png'),
  ('/badges/sample/s054.png'),
  ('/badges/sample/s055.png'),
  ('/badges/sample/s056.png'),
  ('/badges/sample/s057.png'),
  ('/badges/sample/s058.png'),
  ('/badges/sample/s059.png'),
  ('/badges/sample/s060.png'),
  ('/badges/sample/s061.png'),
  ('/badges/sample/s062.png'),
  ('/badges/sample/s063.png'),
  ('/badges/sample/s064.png'),
  ('/badges/sample/s065.png'),
  ('/badges/sample/s066.png'),
  ('/badges/sample/s067.png'),
  ('/badges/sample/s068.png'),
  ('/badges/sample/s069.png'),
  ('/badges/sample/s070.png'),
  ('/badges/sample/s071.png'),
  ('/badges/sample/s072.png'),
  ('/badges/sample/s073.png'),
  ('/badges/sample/s074.png'),
  ('/badges/sample/s075.png'),
  ('/badges/sample/s076.png'),
  ('/badges/sample/s077.png'),
  ('/badges/sample/s078.png'),
  ('/badges/sample/s079.png'),
  ('/badges/sample/s080.png'),
  ('/badges/sample/s081.png'),
  ('/badges/sample/s082.png'),
  ('/badges/sample/s083.png'),
  ('/badges/sample/s084.png'),
  ('/badges/sample/s085.png'),
  ('/badges/sample/s086.png'),
  ('/badges/sample/s087.png'),
  ('/badges/sample/s088.png'),
  ('/badges/sample/s089.png'),
  ('/badges/sample/s090.png'),
  ('/badges/sample/s091.png'),
  ('/badges/sample/s092.png'),
  ('/badges/sample/s093.png'),
  ('/badges/sample/s094.png'),
  ('/badges/sample/s095.png'),
  ('/badges/sample/s096.png'),
  ('/badges/sample/s097.png'),
  ('/badges/sample/s098.png'),
  ('/badges/sample/s099.png'),
  ('/badges/sample/s100.png'),
  ('/badges/sample/s101.png'),
  ('/badges/sample/s102.png'),
  ('/badges/sample/s103.png'),
  ('/badges/sample/s104.png'),
  ('/badges/sample/s105.png'),
  ('/badges/sample/s106.png'),
  ('/badges/sample/s107.png'),
  ('/badges/sample/s108.png'),
  ('/badges/sample/s109.png'),
  ('/badges/sample/s110.png'),
  ('/badges/sample/s111.png'),
  ('/badges/sample/s112.png'),
  ('/badges/sample/s113.png'),
  ('/badges/sample/s114.png'),
  ('/badges/sample/s115.png'),
  ('/badges/sample/s116.png'),
  ('/badges/sample/s117.png'),
  ('/badges/sample/s118.png'),
  ('/badges/sample/s119.png'),
  ('/badges/sample/s120.png'),
  ('/badges/sample/s121.png'),
  ('/badges/sample/s122.png'),
  ('/badges/sample/s123.png'),
  ('/badges/sample/s124.png'),
  ('/badges/sample/s125.png'),
  ('/badges/sample/s126.png'),
  ('/badges/sample/s127.png'),
  ('/badges/sample/s128.png'),
  ('/badges/sample/s129.png'),
  ('/badges/sample/s130.png'),
  ('/badges/sample/s131.png'),
  ('/badges/sample/s132.png'),
  ('/badges/sample/s133.png'),
  ('/badges/sample/s134.png'),
  ('/badges/sample/s135.png'),
  ('/badges/sample/s136.png'),
  ('/badges/sample/s137.png'),
  ('/badges/sample/s138.png'),
  ('/badges/sample/s139.png'),
  ('/badges/sample/s140.png'),
  ('/badges/sample/s141.png'),
  ('/badges/sample/s142.png'),
  ('/badges/sample/s143.png'),
  ('/badges/sample/s144.png'),
  ('/badges/sample/s145.png'),
  ('/badges/sample/s146.png'),
  ('/badges/sample/s147.png'),
  ('/badges/sample/s148.png'),
  ('/badges/sample/s149.png'),
  ('/badges/sample/s150.png'),
  ('/badges/sample/s151.png'),
  ('/badges/sample/s152.png'),
  ('/badges/sample/s153.png'),
  ('/badges/sample/s154.png'),
  ('/badges/sample/s155.png'),
  ('/badges/sample/s156.png'),
  ('/badges/sample/s157.png'),
  ('/badges/sample/s158.png'),
  ('/badges/sample/s159.png'),
  ('/badges/sample/s160.png'),
  ('/badges/sample/s161.png'),
  ('/badges/sample/s162.png'),
  ('/badges/sample/s163.png'),
  ('/badges/sample/s164.png'),
  ('/badges/sample/s165.png'),
  ('/badges/sample/s166.png'),
  ('/badges/sample/s167.png'),
  ('/badges/sample/s168.png'),
  ('/badges/sample/s169.png'),
  ('/badges/sample/s170.png'),
  ('/badges/sample/s171.png'),
  ('/badges/sample/s172.png'),
  ('/badges/sample/s173.png'),
  ('/badges/sample/s174.png'),
  ('/badges/sample/s175.png'),
  ('/badges/sample/s176.png'),
  ('/badges/sample/s177.png'),
  ('/badges/sample/s178.png'),
  ('/badges/sample/s179.png'),
  ('/badges/sample/s180.png'),
  ('/badges/sample/s181.png'),
  ('/badges/sample/s182.png'),
  ('/badges/sample/s183.png'),
  ('/badges/sample/s184.png'),
  ('/badges/sample/s185.png'),
  ('/badges/sample/s186.png'),
  ('/badges/sample/s187.png'),
  ('/badges/sample/s188.png'),
  ('/badges/sample/s189.png'),
  ('/badges/sample/s190.png'),
  ('/badges/sample/s191.png'),
  ('/badges/sample/s192.png'),
  ('/badges/sample/s193.png'),
  ('/badges/sample/s194.png'),
  ('/badges/sample/s195.png'),
  ('/badges/sample/s196.png'),
  ('/badges/sample/s197.png'),
  ('/badges/sample/s198.png'),
  ('/badges/sample/s199.png'),
  ('/badges/sample/s200.png'),
  ('/badges/sample/s201.png'),
  ('/badges/sample/s202.png'),
  ('/badges/sample/s203.png'),
  ('/badges/sample/s204.png'),
  ('/badges/sample/s205.png'),
  ('/badges/sample/s206.png'),
  ('/badges/sample/s207.png'),
  ('/badges/sample/s208.png'),
  ('/badges/sample/s209.png'),
  ('/badges/sample/s210.png'),
  ('/badges/sample/s211.png'),
  ('/badges/sample/s212.png'),
  ('/badges/sample/s213.png'),
  ('/badges/sample/s214.png'),
  ('/badges/sample/s215.png'),
  ('/badges/sample/s216.png'),
  ('/badges/sample/s217.png'),
  ('/badges/sample/s218.png'),
  ('/badges/sample/s219.png'),
  ('/badges/sample/s220.png'),
  ('/badges/sample/s221.png'),
  ('/badges/sample/s222.png'),
  ('/badges/sample/s223.png'),
  ('/badges/sample/s224.png'),
  ('/badges/sample/s225.png'),
  ('/badges/sample/s226.png'),
  ('/badges/sample/s227.png'),
  ('/badges/sample/s228.png'),
  ('/badges/sample/s229.png'),
  ('/badges/sample/s230.png'),
  ('/badges/sample/s231.png'),
  ('/badges/sample/s232.png'),
  ('/badges/sample/s233.png'),
  ('/badges/sample/s234.png'),
  ('/badges/sample/s235.png'),
  ('/badges/sample/s236.png'),
  ('/badges/sample/s237.png'),
  ('/badges/sample/s238.png'),
  ('/badges/sample/s239.png'),
  ('/badges/sample/s240.png'),
  ('/badges/sample/s241.png'),
  ('/badges/sample/s242.png'),
  ('/badges/sample/s243.png'),
  ('/badges/sample/s244.png'),
  ('/badges/sample/s245.png'),
  ('/badges/sample/s246.png'),
  ('/badges/sample/s247.png'),
  ('/badges/sample/s248.png'),
  ('/badges/sample/s249.png'),
  ('/badges/sample/s250.png'),
  ('/badges/sample/s251.png'),
  ('/badges/sample/s252.png'),
  ('/badges/sample/s253.png'),
  ('/badges/sample/s254.png'),
  ('/badges/sample/s255.png'),
  ('/badges/sample/s256.png'),
  ('/badges/sample/s257.png'),
  ('/badges/sample/s258.png'),
  ('/badges/sample/s259.png'),
  ('/badges/sample/s260.png'),
  ('/badges/sample/s261.png'),
  ('/badges/sample/s262.png'),
  ('/badges/sample/s263.png'),
  ('/badges/sample/s264.png'),
  ('/badges/sample/s265.png'),
  ('/badges/sample/s266.png'),
  ('/badges/sample/s267.png'),
  ('/badges/sample/s268.png'),
  ('/badges/sample/s269.png'),
  ('/badges/sample/s270.png'),
  ('/badges/sample/s271.png'),
  ('/badges/sample/s272.png'),
  ('/badges/sample/s273.png'),
  ('/badges/sample/s274.png'),
  ('/badges/sample/s275.png'),
  ('/badges/sample/s276.png'),
  ('/badges/sample/s277.png'),
  ('/badges/sample/s278.png'),
  ('/badges/sample/s279.png'),
  ('/badges/sample/s280.png'),
  ('/badges/sample/s281.png'),
  ('/badges/sample/s282.png'),
  ('/badges/sample/s283.png'),
  ('/badges/sample/s284.png'),
  ('/badges/sample/s285.png'),
  ('/badges/sample/s286.png'),
  ('/badges/sample/s287.png'),
  ('/badges/sample/s288.png'),
  ('/badges/sample/s289.png'),
  ('/badges/sample/s290.png'),
  ('/badges/sample/s291.png'),
  ('/badges/sample/s292.png'),
  ('/badges/sample/s293.png'),
  ('/badges/sample/s294.png'),
  ('/badges/sample/s295.png'),
  ('/badges/sample/s296.png'),
  ('/badges/sample/s297.png'),
  ('/badges/sample/s298.png'),
  ('/badges/sample/s299.png'),
  ('/badges/sample/s300.png'),
  ('/badges/sample/s301.png'),
  ('/badges/sample/s302.png'),
  ('/badges/sample/s303.png'),
  ('/badges/sample/s304.png'),
  ('/badges/sample/s305.png'),
  ('/badges/sample/s306.png'),
  ('/badges/sample/s307.png'),
  ('/badges/sample/s308.png'),
  ('/badges/sample/s309.png'),
  ('/badges/sample/s310.png'),
  ('/badges/sample/s311.png'),
  ('/badges/sample/s312.png'),
  ('/badges/sample/s313.png'),
  ('/badges/sample/s314.png'),
  ('/badges/sample/s315.png'),
  ('/badges/sample/s316.png'),
  ('/badges/sample/s317.png'),
  ('/badges/sample/s318.png'),
  ('/badges/sample/s319.png'),
  ('/badges/sample/s320.png'),
  ('/badges/sample/s321.png'),
  ('/badges/sample/s322.png'),
  ('/badges/sample/s323.png'),
  ('/badges/sample/s324.png'),
  ('/badges/sample/s325.png'),
  ('/badges/sample/s326.png'),
  ('/badges/sample/s327.png'),
  ('/badges/sample/s328.png'),
  ('/badges/sample/s329.png'),
  ('/badges/sample/s330.png'),
  ('/badges/sample/s331.png'),
  ('/badges/sample/s332.png'),
  ('/badges/sample/s333.png'),
  ('/badges/sample/s334.png'),
  ('/badges/sample/s335.png'),
  ('/badges/sample/s336.png'),
  ('/badges/sample/s337.png'),
  ('/badges/sample/s338.png'),
  ('/badges/sample/s339.png'),
  ('/badges/sample/s340.png'),
  ('/badges/sample/s341.png'),
  ('/badges/sample/s342.png'),
  ('/badges/sample/s343.png'),
  ('/badges/sample/s344.png'),
  ('/badges/sample/s345.png'),
  ('/badges/sample/s346.png'),
  ('/badges/sample/s347.png'),
  ('/badges/sample/s348.png'),
  ('/badges/sample/s349.png'),
  ('/badges/sample/s350.png'),
  ('/badges/sample/s351.png'),
  ('/badges/sample/s352.png'),
  ('/badges/sample/s353.png'),
  ('/badges/sample/s354.png'),
  ('/badges/sample/s355.png'),
  ('/badges/sample/s356.png'),
  ('/badges/sample/s357.png'),
  ('/badges/sample/s358.png'),
  ('/badges/sample/s359.png'),
  ('/badges/sample/s360.png'),
  ('/badges/sample/s361.png'),
  ('/badges/sample/s362.png'),
  ('/badges/sample/s363.png'),
  ('/badges/sample/s364.png'),
  ('/badges/sample/s365.png'),
  ('/badges/sample/s366.png'),
  ('/badges/sample/s367.png'),
  ('/badges/sample/s368.png'),
  ('/badges/sample/s369.png'),
  ('/badges/sample/s370.png'),
  ('/badges/sample/s371.png'),
  ('/badges/sample/s372.png')
  ) AS v(path)
),
pool_size AS (
  SELECT count(*) AS n FROM pool
),
targets AS (
  SELECT id, row_number() OVER (ORDER BY random()) AS rn
  FROM public.badges
  WHERE image_url = '/badges/activity-placeholder.png'
     OR image_url LIKE '/badges/sample/%'
)
UPDATE public.badges b
SET image_url = p.path
FROM targets t
JOIN pool p ON ((t.rn - 1) % (SELECT n FROM pool_size)) + 1 = p.rn
WHERE b.id = t.id;

COMMIT;

-- 검증 쿼리:
-- SELECT image_url, count(*) FROM badges
--   WHERE image_url LIKE '/badges/sample/%'
--   GROUP BY image_url ORDER BY count(*) DESC;
-- → 372개 행, 각 count가 2~3 근처로 고르게 분포해야 정상 (한 값에 몰리면 재발)
--
-- SELECT count(*) FROM badges WHERE image_url = '/badges/activity-placeholder.png';
-- → 0이어야 정상 (활동배지도 전부 교체됨)
