-- 배지 이미지 100종을 첨부 스티커 에셋 기반으로 교체 (placehold.co -> /badges/*.png)
UPDATE public.badges SET image_url = '/badges/001.png' WHERE name = '첫 페달';
UPDATE public.badges SET image_url = '/badges/002.png' WHERE name = '한강 라이더';
UPDATE public.badges SET image_url = '/badges/003.png' WHERE name = '자전거 마스터';
UPDATE public.badges SET image_url = '/badges/004.png' WHERE name = '국토종주 챌린저';
UPDATE public.badges SET image_url = '/badges/005.png' WHERE name = '천 킬로미터의 전설';
UPDATE public.badges SET image_url = '/badges/006.png' WHERE name = '첫 발자국';
UPDATE public.badges SET image_url = '/badges/007.png' WHERE name = '동네 한 바퀴';
UPDATE public.badges SET image_url = '/badges/008.png' WHERE name = '러너스 하이';
UPDATE public.badges SET image_url = '/badges/009.png' WHERE name = '마라톤 크루';
UPDATE public.badges SET image_url = '/badges/010.png' WHERE name = '천 킬로미터의 전설 (러너)';
UPDATE public.badges SET image_url = '/badges/011.png' WHERE name = '첫 산행';
UPDATE public.badges SET image_url = '/badges/012.png' WHERE name = '뒷산 단골';
UPDATE public.badges SET image_url = '/badges/013.png' WHERE name = '능선의 친구';
UPDATE public.badges SET image_url = '/badges/014.png' WHERE name = '백대명산 순례자';
UPDATE public.badges SET image_url = '/badges/015.png' WHERE name = '천 킬로미터의 전설 (산악인)';
UPDATE public.badges SET image_url = '/badges/016.png' WHERE name = '첫 만보';
UPDATE public.badges SET image_url = '/badges/017.png' WHERE name = '동네 산책러';
UPDATE public.badges SET image_url = '/badges/018.png' WHERE name = '만보 워커';
UPDATE public.badges SET image_url = '/badges/019.png' WHERE name = '도보 여행가';
UPDATE public.badges SET image_url = '/badges/020.png' WHERE name = '천 킬로미터의 전설 (워커)';
UPDATE public.badges SET image_url = '/badges/021.png' WHERE name = '라이딩 입문';
UPDATE public.badges SET image_url = '/badges/022.png' WHERE name = '라이딩 습관러';
UPDATE public.badges SET image_url = '/badges/023.png' WHERE name = '라이딩 마니아';
UPDATE public.badges SET image_url = '/badges/024.png' WHERE name = '백 라이더';
UPDATE public.badges SET image_url = '/badges/025.png' WHERE name = '러닝 입문';
UPDATE public.badges SET image_url = '/badges/026.png' WHERE name = '러닝 습관러';
UPDATE public.badges SET image_url = '/badges/027.png' WHERE name = '러닝 마니아';
UPDATE public.badges SET image_url = '/badges/028.png' WHERE name = '센츄리 러너';
UPDATE public.badges SET image_url = '/badges/029.png' WHERE name = '산행 입문';
UPDATE public.badges SET image_url = '/badges/030.png' WHERE name = '산행 습관러';
UPDATE public.badges SET image_url = '/badges/031.png' WHERE name = '산행 마니아';
UPDATE public.badges SET image_url = '/badges/032.png' WHERE name = '백대명산 정복자';
UPDATE public.badges SET image_url = '/badges/033.png' WHERE name = '걷기 입문';
UPDATE public.badges SET image_url = '/badges/034.png' WHERE name = '걷기 습관러';
UPDATE public.badges SET image_url = '/badges/035.png' WHERE name = '걷기 마니아';
UPDATE public.badges SET image_url = '/badges/036.png' WHERE name = '만보 마스터';
UPDATE public.badges SET image_url = '/badges/037.png' WHERE name = '3일 연속 라이더';
UPDATE public.badges SET image_url = '/badges/038.png' WHERE name = '위클리 라이더';
UPDATE public.badges SET image_url = '/badges/039.png' WHERE name = '30일 연속 라이더의 전설';
UPDATE public.badges SET image_url = '/badges/040.png' WHERE name = '3일 연속 러너';
UPDATE public.badges SET image_url = '/badges/041.png' WHERE name = '위클리 러너';
UPDATE public.badges SET image_url = '/badges/042.png' WHERE name = '30일 연속 러너의 전설';
UPDATE public.badges SET image_url = '/badges/043.png' WHERE name = '3일 연속 산행러';
UPDATE public.badges SET image_url = '/badges/044.png' WHERE name = '위클리 산행러';
UPDATE public.badges SET image_url = '/badges/045.png' WHERE name = '30일 연속 산행러의 전설';
UPDATE public.badges SET image_url = '/badges/046.png' WHERE name = '3일 연속 워커';
UPDATE public.badges SET image_url = '/badges/047.png' WHERE name = '위클리 워커';
UPDATE public.badges SET image_url = '/badges/048.png' WHERE name = '30일 연속 워커의 전설';
UPDATE public.badges SET image_url = '/badges/049.png' WHERE name = '첫 오르막';
UPDATE public.badges SET image_url = '/badges/050.png' WHERE name = '관악산 정복자';
UPDATE public.badges SET image_url = '/badges/051.png' WHERE name = '지리산 종주자';
UPDATE public.badges SET image_url = '/badges/052.png' WHERE name = '백두대간 마스터';
UPDATE public.badges SET image_url = '/badges/053.png' WHERE name = '첫 언덕';
UPDATE public.badges SET image_url = '/badges/054.png' WHERE name = '자전거 힐클라이머';
UPDATE public.badges SET image_url = '/badges/055.png' WHERE name = '미시령 정복자';
UPDATE public.badges SET image_url = '/badges/056.png' WHERE name = '그란폰도 마스터';
UPDATE public.badges SET image_url = '/badges/057.png' WHERE name = '스피드 입문';
UPDATE public.badges SET image_url = '/badges/058.png' WHERE name = '스피드 라이더';
UPDATE public.badges SET image_url = '/badges/059.png' WHERE name = '스피드 킹';
UPDATE public.badges SET image_url = '/badges/060.png' WHERE name = '조깅 페이스';
UPDATE public.badges SET image_url = '/badges/061.png' WHERE name = '러닝 페이스';
UPDATE public.badges SET image_url = '/badges/062.png' WHERE name = '스프린터';
UPDATE public.badges SET image_url = '/badges/063.png' WHERE name = '남산 정복자';
UPDATE public.badges SET image_url = '/badges/064.png' WHERE name = '뚝섬 라이더';
UPDATE public.badges SET image_url = '/badges/065.png' WHERE name = '북악스카이웨이 클라이머';
UPDATE public.badges SET image_url = '/badges/066.png' WHERE name = '청계산 완주자';
UPDATE public.badges SET image_url = '/badges/067.png' WHERE name = '광나루 라이더';
UPDATE public.badges SET image_url = '/badges/068.png' WHERE name = '운동의 시작';
UPDATE public.badges SET image_url = '/badges/069.png' WHERE name = '올라운더';
UPDATE public.badges SET image_url = '/badges/070.png' WHERE name = '백일 개근상';
UPDATE public.badges SET image_url = '/badges/071.png' WHERE name = '기본 체인링 패치';
UPDATE public.badges SET image_url = '/badges/072.png' WHERE name = '산길 리본 패치';
UPDATE public.badges SET image_url = '/badges/073.png' WHERE name = '러닝화 스티커';
UPDATE public.badges SET image_url = '/badges/074.png' WHERE name = '발걸음 배지';
UPDATE public.badges SET image_url = '/badges/075.png' WHERE name = '초록 이파리 패치';
UPDATE public.badges SET image_url = '/badges/076.png' WHERE name = '노을 패치';
UPDATE public.badges SET image_url = '/badges/077.png' WHERE name = '물방울 패치';
UPDATE public.badges SET image_url = '/badges/078.png' WHERE name = '자전거 벨 패치';
UPDATE public.badges SET image_url = '/badges/079.png' WHERE name = '등산 스틱 패치';
UPDATE public.badges SET image_url = '/badges/080.png' WHERE name = '페이스메이커 패치';
UPDATE public.badges SET image_url = '/badges/081.png' WHERE name = '만보기 패치';
UPDATE public.badges SET image_url = '/badges/082.png' WHERE name = '아침이슬 패치';
UPDATE public.badges SET image_url = '/badges/083.png' WHERE name = '홀로그램 체인링 패치';
UPDATE public.badges SET image_url = '/badges/084.png' WHERE name = '산악회 정예 리본';
UPDATE public.badges SET image_url = '/badges/085.png' WHERE name = '네온 러닝화 스티커';
UPDATE public.badges SET image_url = '/badges/086.png' WHERE name = '도시 걷기 마스터 패치';
UPDATE public.badges SET image_url = '/badges/087.png' WHERE name = '은빛 자전거 패치';
UPDATE public.badges SET image_url = '/badges/088.png' WHERE name = '청계산 실버 리본';
UPDATE public.badges SET image_url = '/badges/089.png' WHERE name = '한강 야경 패치';
UPDATE public.badges SET image_url = '/badges/090.png' WHERE name = '스피드러너 패치';
UPDATE public.badges SET image_url = '/badges/091.png' WHERE name = '계절풍 패치';
UPDATE public.badges SET image_url = '/badges/092.png' WHERE name = '도심 산책자 패치';
UPDATE public.badges SET image_url = '/badges/093.png' WHERE name = '골드 체인링 패치';
UPDATE public.badges SET image_url = '/badges/094.png' WHERE name = '백두대간 전설 리본';
UPDATE public.badges SET image_url = '/badges/095.png' WHERE name = '마라토너 골드 스티커';
UPDATE public.badges SET image_url = '/badges/096.png' WHERE name = '도보 여행가 패치';
UPDATE public.badges SET image_url = '/badges/097.png' WHERE name = '오로라 사이클 패치';
UPDATE public.badges SET image_url = '/badges/098.png' WHERE name = '산신령의 축복 패치';
UPDATE public.badges SET image_url = '/badges/099.png' WHERE name = '무지개 체인링 패치';
UPDATE public.badges SET image_url = '/badges/100.png' WHERE name = '전설의 산악인 패치';
